// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type AIAction struct {
	Sys           string `json:"sys"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Configuration string `json:"configuration"`
	Instruction   string `json:"instruction"`
}

type APIKey struct {
	Sys          string `json:"sys"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	AccessToken  string `json:"accessToken"`
	Environments string `json:"environments"`
}

type AppInstallation struct {
	Sys        string `json:"sys"`
	Parameters string `json:"parameters"`
}

type Asset struct {
	Sys    string `json:"sys"`
	Fields string `json:"fields"`
}

type Comment struct {
	Sys    string `json:"sys"`
	Body   string `json:"body"`
	Status string `json:"status"`
}

type ContentType struct {
	Sys          string `json:"sys"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	DisplayField string `json:"displayField"`
	Fields       string `json:"fields"`
}

type EditorInterface struct {
	Sys      string `json:"sys"`
	Controls string `json:"controls"`
	Sidebar  string `json:"sidebar"`
}

type Entry struct {
	Sys      string `json:"sys"`
	Fields   string `json:"fields"`
	Metadata string `json:"metadata"`
}

type Environment struct {
	Sys  string `json:"sys"`
	Name string `json:"name"`
}

type EnvironmentAlias struct {
	Sys         string `json:"sys"`
	Environment string `json:"environment"`
}

type Extension struct {
	Sys       string `json:"sys"`
	Extension string `json:"extension"`
}

type Locale struct {
	Sys          string `json:"sys"`
	Name         string `json:"name"`
	Code         string `json:"code"`
	FallbackCode string `json:"fallbackCode"`
	Default      bool   `json:"default"`
	Optional     bool   `json:"optional"`
}

type Organization struct {
	Sys  string `json:"sys"`
	Name string `json:"name"`
}

type OrganizationMembership struct {
	Sys    string `json:"sys"`
	Role   string `json:"role"`
	Status string `json:"status"`
}

type Release struct {
	Sys      string `json:"sys"`
	Title    string `json:"title"`
	Entities string `json:"entities"`
}

type Role struct {
	Sys         string `json:"sys"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ScheduledAction struct {
	Sys          string `json:"sys"`
	Entity       string `json:"entity"`
	Action       string `json:"action"`
	ScheduledFor string `json:"scheduledFor"`
	Status       string `json:"status"`
}

type Snapshot struct {
	Sys      string `json:"sys"`
	Snapshot string `json:"snapshot"`
}

type Space struct {
	Sys  string `json:"sys"`
	Name string `json:"name"`
}

type SpaceMembership struct {
	Sys   string `json:"sys"`
	Admin bool   `json:"admin"`
	Roles string `json:"roles"`
}

type SyncResponse struct {
	Items         string `json:"items"`
	NextSyncToken string `json:"nextSyncToken"`
	NextPageUrl   string `json:"nextPageUrl"`
}

type SysObject struct {
	Id               string `json:"id"`
	Type             string `json:"type"`
	Version          int    `json:"version"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
	PublishedAt      string `json:"publishedAt"`
	PublishedVersion int    `json:"publishedVersion"`
	ArchivedAt       string `json:"archivedAt"`
	ArchivedVersion  int    `json:"archivedVersion"`
	Space            string `json:"space"`
	Environment      string `json:"environment"`
	ContentType      string `json:"contentType"`
}

type Tag struct {
	Sys  string `json:"sys"`
	Name string `json:"name"`
}

type Task struct {
	Sys        string `json:"sys"`
	Body       string `json:"body"`
	AssignedTo string `json:"assignedTo"`
	Status     string `json:"status"`
	DueDate    string `json:"dueDate"`
}

type User struct {
	Sys       string `json:"sys"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	AvatarUrl string `json:"avatarUrl"`
}

type Webhook struct {
	Sys               string `json:"sys"`
	Name              string `json:"name"`
	Url               string `json:"url"`
	Topics            string `json:"topics"`
	HttpBasicUsername string `json:"httpBasicUsername"`
	Transformation    string `json:"transformation"`
}

type WebhookCall struct {
	Sys        string `json:"sys"`
	Request    string `json:"request"`
	Response   string `json:"response"`
	StatusCode int    `json:"statusCode"`
}
