// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("contentful_search",
			mcplib.WithDescription("Search the contentful API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("contentful_execute",
			mcplib.WithDescription("Execute one contentful API endpoint by its endpoint_id (from contentful_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by contentful_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	keywords   []string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:         "ai_actions.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions",
		Tier:       "cma",
		Summary:    "Create an AI Action",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("ai_actions", "create", "Create an AI Action", "/spaces/{space_id}/environments/{environment_id}/ai_actions"),
	},
	{
		ID:         "ai_actions.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}",
		Tier:       "cma",
		Summary:    "Delete an AI Action",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "delete", "Delete an AI Action", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}"),
	},
	{
		ID:         "ai_actions.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}",
		Tier:       "cma",
		Summary:    "Get an AI Action by ID",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "get", "Get an AI Action by ID", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}"),
	},
	{
		ID:         "ai_actions.invocation",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/invocations/{invocation_id}",
		Tier:       "cma",
		Summary:    "Get an AI Action invocation result by ID",
		Positional: []string{"space_id", "environment_id", "ai_action_id", "invocation_id"},
		keywords:   codeOrchKeywords("ai_actions", "invocation", "Get an AI Action invocation result by ID", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/invocations/{invocation_id}"),
	},
	{
		ID:         "ai_actions.invoke",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/invoke",
		Tier:       "cma",
		Summary:    "Invoke an AI Action (returns an invocation ID; poll with invocation)",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "invoke", "Invoke an AI Action (returns an invocation ID; poll with invocation)", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/invoke"),
	},
	{
		ID:         "ai_actions.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions",
		Tier:       "cma",
		Summary:    "List AI Actions",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("ai_actions", "list", "List AI Actions", "/spaces/{space_id}/environments/{environment_id}/ai_actions"),
	},
	{
		ID:         "ai_actions.publish",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/published",
		Tier:       "cma",
		Summary:    "Publish an AI Action (no body; requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "publish", "Publish an AI Action (no body; requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/published"),
	},
	{
		ID:         "ai_actions.unpublish",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/published",
		Tier:       "cma",
		Summary:    "Unpublish an AI Action",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "unpublish", "Unpublish an AI Action", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}/published"),
	},
	{
		ID:         "ai_actions.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}",
		Tier:       "cma",
		Summary:    "Update an AI Action (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "ai_action_id"},
		keywords:   codeOrchKeywords("ai_actions", "update", "Update an AI Action (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/ai_actions/{ai_action_id}"),
	},
	{
		ID:         "api_keys.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/api_keys",
		Tier:       "cma",
		Summary:    "Create a delivery API key",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("api_keys", "create", "Create a delivery API key", "/spaces/{space_id}/api_keys"),
	},
	{
		ID:         "api_keys.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/api_keys/{api_key_id}",
		Tier:       "cma",
		Summary:    "Delete a delivery API key",
		Positional: []string{"space_id", "api_key_id"},
		keywords:   codeOrchKeywords("api_keys", "delete", "Delete a delivery API key", "/spaces/{space_id}/api_keys/{api_key_id}"),
	},
	{
		ID:         "api_keys.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/api_keys/{api_key_id}",
		Tier:       "cma",
		Summary:    "Get a delivery API key by ID",
		Positional: []string{"space_id", "api_key_id"},
		keywords:   codeOrchKeywords("api_keys", "get", "Get a delivery API key by ID", "/spaces/{space_id}/api_keys/{api_key_id}"),
	},
	{
		ID:         "api_keys.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/api_keys",
		Tier:       "cma",
		Summary:    "List delivery API keys",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("api_keys", "list", "List delivery API keys", "/spaces/{space_id}/api_keys"),
	},
	{
		ID:         "api_keys.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/api_keys/{api_key_id}",
		Tier:       "cma",
		Summary:    "Update a delivery API key (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "api_key_id"},
		keywords:   codeOrchKeywords("api_keys", "update", "Update a delivery API key (requires X-Contentful-Version header)", "/spaces/{space_id}/api_keys/{api_key_id}"),
	},
	{
		ID:         "app_installations.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}",
		Tier:       "cma",
		Summary:    "Get an app installation by app definition ID",
		Positional: []string{"space_id", "environment_id", "app_definition_id"},
		keywords:   codeOrchKeywords("app_installations", "get", "Get an app installation by app definition ID", "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}"),
	},
	{
		ID:         "app_installations.install",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}",
		Tier:       "cma",
		Summary:    "Install or reconfigure an app",
		Positional: []string{"space_id", "environment_id", "app_definition_id"},
		keywords:   codeOrchKeywords("app_installations", "install", "Install or reconfigure an app", "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}"),
	},
	{
		ID:         "app_installations.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/app_installations",
		Tier:       "cma",
		Summary:    "List app installations",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("app_installations", "list", "List app installations", "/spaces/{space_id}/environments/{environment_id}/app_installations"),
	},
	{
		ID:         "app_installations.uninstall",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}",
		Tier:       "cma",
		Summary:    "Uninstall an app",
		Positional: []string{"space_id", "environment_id", "app_definition_id"},
		keywords:   codeOrchKeywords("app_installations", "uninstall", "Uninstall an app", "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}"),
	},
	{
		ID:         "assets.archive",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/archived",
		Tier:       "cma",
		Summary:    "Archive an asset (no body)",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "archive", "Archive an asset (no body)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/archived"),
	},
	{
		ID:         "assets.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets",
		Tier:       "cma",
		Summary:    "Create an asset (metadata only — call assets process to ingest binary)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("assets", "create", "Create an asset (metadata only — call assets process to ingest binary)", "/spaces/{space_id}/environments/{environment_id}/assets"),
	},
	{
		ID:         "assets.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}",
		Tier:       "cma",
		Summary:    "Delete an asset",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "delete", "Delete an asset", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}"),
	},
	{
		ID:         "assets.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}",
		Tier:       "cma",
		Summary:    "Get an asset by ID",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "get", "Get an asset by ID", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}"),
	},
	{
		ID:         "assets.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets",
		Tier:       "cma",
		Summary:    "List assets in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("assets", "list", "List assets in an environment", "/spaces/{space_id}/environments/{environment_id}/assets"),
	},
	{
		ID:         "assets.process",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/files/{locale}/process",
		Tier:       "cma",
		Summary:    "Trigger asset processing for a specific locale (no body)",
		Positional: []string{"space_id", "environment_id", "asset_id", "locale"},
		keywords:   codeOrchKeywords("assets", "process", "Trigger asset processing for a specific locale (no body)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/files/{locale}/process"),
	},
	{
		ID:         "assets.publish",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/published",
		Tier:       "cma",
		Summary:    "Publish an asset (no body; requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "publish", "Publish an asset (no body; requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/published"),
	},
	{
		ID:         "assets.unarchive",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/archived",
		Tier:       "cma",
		Summary:    "Unarchive an asset",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "unarchive", "Unarchive an asset", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/archived"),
	},
	{
		ID:         "assets.unpublish",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/published",
		Tier:       "cma",
		Summary:    "Unpublish an asset",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "unpublish", "Unpublish an asset", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}/published"),
	},
	{
		ID:         "assets.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}",
		Tier:       "cma",
		Summary:    "Update asset metadata (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("assets", "update", "Update asset metadata (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}"),
	},
	{
		ID:         "comments.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments",
		Tier:       "cma",
		Summary:    "Create a comment on an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("comments", "create", "Create a comment on an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments"),
	},
	{
		ID:         "comments.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}",
		Tier:       "cma",
		Summary:    "Delete a comment",
		Positional: []string{"space_id", "environment_id", "entry_id", "comment_id"},
		keywords:   codeOrchKeywords("comments", "delete", "Delete a comment", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}"),
	},
	{
		ID:         "comments.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}",
		Tier:       "cma",
		Summary:    "Get a comment by ID",
		Positional: []string{"space_id", "environment_id", "entry_id", "comment_id"},
		keywords:   codeOrchKeywords("comments", "get", "Get a comment by ID", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}"),
	},
	{
		ID:         "comments.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments",
		Tier:       "cma",
		Summary:    "List comments on an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("comments", "list", "List comments on an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments"),
	},
	{
		ID:         "comments.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}",
		Tier:       "cma",
		Summary:    "Update a comment (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "entry_id", "comment_id"},
		keywords:   codeOrchKeywords("comments", "update", "Update a comment (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/comments/{comment_id}"),
	},
	{
		ID:         "content_type_snapshots.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/snapshots/{snapshot_id}",
		Tier:       "cma",
		Summary:    "Get a single content type snapshot",
		Positional: []string{"space_id", "environment_id", "content_type_id", "snapshot_id"},
		keywords:   codeOrchKeywords("content_type_snapshots", "get", "Get a single content type snapshot", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/snapshots/{snapshot_id}"),
	},
	{
		ID:         "content_type_snapshots.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/snapshots",
		Tier:       "cma",
		Summary:    "List snapshots for a content type",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_type_snapshots", "list", "List snapshots for a content type", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/snapshots"),
	},
	{
		ID:         "content_types.create",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}",
		Tier:       "cma",
		Summary:    "Create a content type with the given ID",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "create", "Create a content type with the given ID", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}"),
	},
	{
		ID:         "content_types.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}",
		Tier:       "cma",
		Summary:    "Delete a content type",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "delete", "Delete a content type", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}"),
	},
	{
		ID:         "content_types.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}",
		Tier:       "cma",
		Summary:    "Get a content type by ID",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "get", "Get a content type by ID", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}"),
	},
	{
		ID:         "content_types.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types",
		Tier:       "cma",
		Summary:    "List content types in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("content_types", "list", "List content types in an environment", "/spaces/{space_id}/environments/{environment_id}/content_types"),
	},
	{
		ID:         "content_types.publish",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published",
		Tier:       "cma",
		Summary:    "Publish a content type (no body; requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "publish", "Publish a content type (no body; requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published"),
	},
	{
		ID:         "content_types.unpublish",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published",
		Tier:       "cma",
		Summary:    "Unpublish a content type",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "unpublish", "Unpublish a content type", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/published"),
	},
	{
		ID:         "content_types.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}",
		Tier:       "cma",
		Summary:    "Update a content type (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("content_types", "update", "Update a content type (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}"),
	},
	{
		ID:         "delivery_assets.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}",
		Tier:       "cda",
		Summary:    "Get a published asset by ID (CDA)",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("delivery_assets", "get", "Get a published asset by ID (CDA)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}"),
	},
	{
		ID:         "delivery_assets.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets",
		Tier:       "cda",
		Summary:    "List published assets (CDA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("delivery_assets", "list", "List published assets (CDA)", "/spaces/{space_id}/environments/{environment_id}/assets"),
	},
	{
		ID:         "delivery_content_types.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}",
		Tier:       "cda",
		Summary:    "Get a content type by ID (CDA)",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("delivery_content_types", "get", "Get a content type by ID (CDA)", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}"),
	},
	{
		ID:         "delivery_content_types.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types",
		Tier:       "cda",
		Summary:    "List content types (CDA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("delivery_content_types", "list", "List content types (CDA)", "/spaces/{space_id}/environments/{environment_id}/content_types"),
	},
	{
		ID:         "delivery_entries.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}",
		Tier:       "cda",
		Summary:    "Get a published entry by ID (CDA)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("delivery_entries", "get", "Get a published entry by ID (CDA)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}"),
	},
	{
		ID:         "delivery_entries.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries",
		Tier:       "cda",
		Summary:    "List published entries (CDA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("delivery_entries", "list", "List published entries (CDA)", "/spaces/{space_id}/environments/{environment_id}/entries"),
	},
	{
		ID:         "delivery_locales.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales",
		Tier:       "cda",
		Summary:    "List locales (CDA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("delivery_locales", "list", "List locales (CDA)", "/spaces/{space_id}/environments/{environment_id}/locales"),
	},
	{
		ID:         "delivery_sync.run",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/sync",
		Tier:       "cda",
		Summary:    "Full or incremental sync. Use --initial=true once, then --sync-token from the prior nextSyncToken.",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("delivery_sync", "run", "Full or incremental sync. Use --initial=true once, then --sync-token from the prior nextSyncToken.", "/spaces/{space_id}/environments/{environment_id}/sync"),
	},
	{
		ID:         "editor_interfaces.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface",
		Tier:       "cma",
		Summary:    "Get the editor interface for a content type",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("editor_interfaces", "get", "Get the editor interface for a content type", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface"),
	},
	{
		ID:         "editor_interfaces.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/editor_interfaces",
		Tier:       "cma",
		Summary:    "List editor interfaces in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("editor_interfaces", "list", "List editor interfaces in an environment", "/spaces/{space_id}/environments/{environment_id}/editor_interfaces"),
	},
	{
		ID:         "editor_interfaces.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface",
		Tier:       "cma",
		Summary:    "Update the editor interface for a content type (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "content_type_id"},
		keywords:   codeOrchKeywords("editor_interfaces", "update", "Update the editor interface for a content type (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/content_types/{content_type_id}/editor_interface"),
	},
	{
		ID:         "entries.archive",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/archived",
		Tier:       "cma",
		Summary:    "Archive an entry (no body)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "archive", "Archive an entry (no body)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/archived"),
	},
	{
		ID:         "entries.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries",
		Tier:       "cma",
		Summary:    "Create an entry (requires X-Contentful-Content-Type header)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("entries", "create", "Create an entry (requires X-Contentful-Content-Type header)", "/spaces/{space_id}/environments/{environment_id}/entries"),
	},
	{
		ID:         "entries.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}",
		Tier:       "cma",
		Summary:    "Delete an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "delete", "Delete an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}"),
	},
	{
		ID:         "entries.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}",
		Tier:       "cma",
		Summary:    "Get an entry by ID",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "get", "Get an entry by ID", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}"),
	},
	{
		ID:         "entries.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries",
		Tier:       "cma",
		Summary:    "List entries in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("entries", "list", "List entries in an environment", "/spaces/{space_id}/environments/{environment_id}/entries"),
	},
	{
		ID:         "entries.publish",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published",
		Tier:       "cma",
		Summary:    "Publish an entry (no body; requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "publish", "Publish an entry (no body; requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published"),
	},
	{
		ID:         "entries.references",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/references",
		Tier:       "cma",
		Summary:    "Get depth-1 references for an entry (online only — for deep refs use the local mirror)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "references", "Get depth-1 references for an entry (online only — for deep refs use the local mirror)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/references"),
	},
	{
		ID:         "entries.unarchive",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/archived",
		Tier:       "cma",
		Summary:    "Unarchive an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "unarchive", "Unarchive an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/archived"),
	},
	{
		ID:         "entries.unpublish",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published",
		Tier:       "cma",
		Summary:    "Unpublish an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "unpublish", "Unpublish an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/published"),
	},
	{
		ID:         "entries.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}",
		Tier:       "cma",
		Summary:    "Update an entry (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entries", "update", "Update an entry (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}"),
	},
	{
		ID:         "entry_snapshots.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/snapshots/{snapshot_id}",
		Tier:       "cma",
		Summary:    "Get a single entry snapshot",
		Positional: []string{"space_id", "environment_id", "entry_id", "snapshot_id"},
		keywords:   codeOrchKeywords("entry_snapshots", "get", "Get a single entry snapshot", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/snapshots/{snapshot_id}"),
	},
	{
		ID:         "entry_snapshots.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/snapshots",
		Tier:       "cma",
		Summary:    "List snapshots for an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("entry_snapshots", "list", "List snapshots for an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/snapshots"),
	},
	{
		ID:         "environment_aliases.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environment_aliases/{alias_id}",
		Tier:       "cma",
		Summary:    "Get an environment alias by ID",
		Positional: []string{"space_id", "alias_id"},
		keywords:   codeOrchKeywords("environment_aliases", "get", "Get an environment alias by ID", "/spaces/{space_id}/environment_aliases/{alias_id}"),
	},
	{
		ID:         "environment_aliases.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environment_aliases",
		Tier:       "cma",
		Summary:    "List environment aliases",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("environment_aliases", "list", "List environment aliases", "/spaces/{space_id}/environment_aliases"),
	},
	{
		ID:         "environment_aliases.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environment_aliases/{alias_id}",
		Tier:       "cma",
		Summary:    "Update an environment alias to point to a different environment",
		Positional: []string{"space_id", "alias_id"},
		keywords:   codeOrchKeywords("environment_aliases", "update", "Update an environment alias to point to a different environment", "/spaces/{space_id}/environment_aliases/{alias_id}"),
	},
	{
		ID:         "environments.create",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}",
		Tier:       "cma",
		Summary:    "Create an environment (optionally branched from a source)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("environments", "create", "Create an environment (optionally branched from a source)", "/spaces/{space_id}/environments/{environment_id}"),
	},
	{
		ID:         "environments.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}",
		Tier:       "cma",
		Summary:    "Delete an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("environments", "delete", "Delete an environment", "/spaces/{space_id}/environments/{environment_id}"),
	},
	{
		ID:         "environments.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}",
		Tier:       "cma",
		Summary:    "Get an environment by ID",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("environments", "get", "Get an environment by ID", "/spaces/{space_id}/environments/{environment_id}"),
	},
	{
		ID:         "environments.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments",
		Tier:       "cma",
		Summary:    "List environments in a space",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("environments", "list", "List environments in a space", "/spaces/{space_id}/environments"),
	},
	{
		ID:         "extensions.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/extensions",
		Tier:       "cma",
		Summary:    "Create an extension",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("extensions", "create", "Create an extension", "/spaces/{space_id}/environments/{environment_id}/extensions"),
	},
	{
		ID:         "extensions.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}",
		Tier:       "cma",
		Summary:    "Delete an extension",
		Positional: []string{"space_id", "environment_id", "extension_id"},
		keywords:   codeOrchKeywords("extensions", "delete", "Delete an extension", "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}"),
	},
	{
		ID:         "extensions.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}",
		Tier:       "cma",
		Summary:    "Get an extension by ID",
		Positional: []string{"space_id", "environment_id", "extension_id"},
		keywords:   codeOrchKeywords("extensions", "get", "Get an extension by ID", "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}"),
	},
	{
		ID:         "extensions.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/extensions",
		Tier:       "cma",
		Summary:    "List extensions",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("extensions", "list", "List extensions", "/spaces/{space_id}/environments/{environment_id}/extensions"),
	},
	{
		ID:         "extensions.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}",
		Tier:       "cma",
		Summary:    "Update an extension (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "extension_id"},
		keywords:   codeOrchKeywords("extensions", "update", "Update an extension (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/extensions/{extension_id}"),
	},
	{
		ID:         "gql.query",
		Method:     "POST",
		Path:       "/content/v1/spaces/{space_id}/environments/{environment_id}",
		Tier:       "gql",
		Summary:    "Run a GraphQL query against a space+environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("gql", "query", "Run a GraphQL query against a space+environment", "/content/v1/spaces/{space_id}/environments/{environment_id}"),
	},
	{
		ID:         "locales.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales",
		Tier:       "cma",
		Summary:    "Create a locale",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("locales", "create", "Create a locale", "/spaces/{space_id}/environments/{environment_id}/locales"),
	},
	{
		ID:         "locales.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}",
		Tier:       "cma",
		Summary:    "Delete a locale",
		Positional: []string{"space_id", "environment_id", "locale_id"},
		keywords:   codeOrchKeywords("locales", "delete", "Delete a locale", "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}"),
	},
	{
		ID:         "locales.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}",
		Tier:       "cma",
		Summary:    "Get a locale by ID",
		Positional: []string{"space_id", "environment_id", "locale_id"},
		keywords:   codeOrchKeywords("locales", "get", "Get a locale by ID", "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}"),
	},
	{
		ID:         "locales.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales",
		Tier:       "cma",
		Summary:    "List locales in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("locales", "list", "List locales in an environment", "/spaces/{space_id}/environments/{environment_id}/locales"),
	},
	{
		ID:         "locales.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}",
		Tier:       "cma",
		Summary:    "Update a locale (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "locale_id"},
		keywords:   codeOrchKeywords("locales", "update", "Update a locale (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/locales/{locale_id}"),
	},
	{
		ID:         "organization_memberships.list",
		Method:     "GET",
		Path:       "/organizations/{organization_id}/organization_memberships",
		Tier:       "cma",
		Summary:    "List members of an organization",
		Positional: []string{"organization_id"},
		keywords:   codeOrchKeywords("organization_memberships", "list", "List members of an organization", "/organizations/{organization_id}/organization_memberships"),
	},
	{
		ID:         "organizations.get",
		Method:     "GET",
		Path:       "/organizations/{organization_id}",
		Tier:       "cma",
		Summary:    "Get an organization by ID",
		Positional: []string{"organization_id"},
		keywords:   codeOrchKeywords("organizations", "get", "Get an organization by ID", "/organizations/{organization_id}"),
	},
	{
		ID:         "organizations.list",
		Method:     "GET",
		Path:       "/organizations",
		Tier:       "cma",
		Summary:    "List organizations the token can access",
		Positional: []string{},
		keywords:   codeOrchKeywords("organizations", "list", "List organizations the token can access", "/organizations"),
	},
	{
		ID:         "preview_api_keys.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/preview_api_keys/{key_id}",
		Tier:       "cma",
		Summary:    "Get a preview API key by ID",
		Positional: []string{"space_id", "key_id"},
		keywords:   codeOrchKeywords("preview_api_keys", "get", "Get a preview API key by ID", "/spaces/{space_id}/preview_api_keys/{key_id}"),
	},
	{
		ID:         "preview_api_keys.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/preview_api_keys",
		Tier:       "cma",
		Summary:    "List preview API keys",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("preview_api_keys", "list", "List preview API keys", "/spaces/{space_id}/preview_api_keys"),
	},
	{
		ID:         "preview_assets.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}",
		Tier:       "cpa",
		Summary:    "Get a draft+published asset by ID (CPA)",
		Positional: []string{"space_id", "environment_id", "asset_id"},
		keywords:   codeOrchKeywords("preview_assets", "get", "Get a draft+published asset by ID (CPA)", "/spaces/{space_id}/environments/{environment_id}/assets/{asset_id}"),
	},
	{
		ID:         "preview_assets.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/assets",
		Tier:       "cpa",
		Summary:    "List assets including drafts (CPA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("preview_assets", "list", "List assets including drafts (CPA)", "/spaces/{space_id}/environments/{environment_id}/assets"),
	},
	{
		ID:         "preview_entries.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}",
		Tier:       "cpa",
		Summary:    "Get an entry including drafts by ID (CPA)",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("preview_entries", "get", "Get an entry including drafts by ID (CPA)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}"),
	},
	{
		ID:         "preview_entries.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries",
		Tier:       "cpa",
		Summary:    "List entries including drafts (CPA)",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("preview_entries", "list", "List entries including drafts (CPA)", "/spaces/{space_id}/environments/{environment_id}/entries"),
	},
	{
		ID:         "release_actions.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/actions/{action_id}",
		Tier:       "cma",
		Summary:    "Get a single release action's status and result",
		Positional: []string{"space_id", "environment_id", "release_id", "action_id"},
		keywords:   codeOrchKeywords("release_actions", "get", "Get a single release action's status and result", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/actions/{action_id}"),
	},
	{
		ID:         "release_actions.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/actions",
		Tier:       "cma",
		Summary:    "List actions performed against a release",
		Positional: []string{"space_id", "environment_id", "release_id"},
		keywords:   codeOrchKeywords("release_actions", "list", "List actions performed against a release", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/actions"),
	},
	{
		ID:         "releases.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases",
		Tier:       "cma",
		Summary:    "Create a release",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("releases", "create", "Create a release", "/spaces/{space_id}/environments/{environment_id}/releases"),
	},
	{
		ID:         "releases.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}",
		Tier:       "cma",
		Summary:    "Delete a release",
		Positional: []string{"space_id", "environment_id", "release_id"},
		keywords:   codeOrchKeywords("releases", "delete", "Delete a release", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}"),
	},
	{
		ID:         "releases.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}",
		Tier:       "cma",
		Summary:    "Get a release by ID",
		Positional: []string{"space_id", "environment_id", "release_id"},
		keywords:   codeOrchKeywords("releases", "get", "Get a release by ID", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}"),
	},
	{
		ID:         "releases.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases",
		Tier:       "cma",
		Summary:    "List releases in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("releases", "list", "List releases in an environment", "/spaces/{space_id}/environments/{environment_id}/releases"),
	},
	{
		ID:         "releases.publish",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/published",
		Tier:       "cma",
		Summary:    "Publish all entities in a release",
		Positional: []string{"space_id", "environment_id", "release_id"},
		keywords:   codeOrchKeywords("releases", "publish", "Publish all entities in a release", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}/published"),
	},
	{
		ID:         "releases.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}",
		Tier:       "cma",
		Summary:    "Update a release (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "release_id"},
		keywords:   codeOrchKeywords("releases", "update", "Update a release (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/releases/{release_id}"),
	},
	{
		ID:         "roles.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/roles",
		Tier:       "cma",
		Summary:    "Create a role",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("roles", "create", "Create a role", "/spaces/{space_id}/roles"),
	},
	{
		ID:         "roles.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/roles/{role_id}",
		Tier:       "cma",
		Summary:    "Delete a role",
		Positional: []string{"space_id", "role_id"},
		keywords:   codeOrchKeywords("roles", "delete", "Delete a role", "/spaces/{space_id}/roles/{role_id}"),
	},
	{
		ID:         "roles.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/roles/{role_id}",
		Tier:       "cma",
		Summary:    "Get a role by ID",
		Positional: []string{"space_id", "role_id"},
		keywords:   codeOrchKeywords("roles", "get", "Get a role by ID", "/spaces/{space_id}/roles/{role_id}"),
	},
	{
		ID:         "roles.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/roles",
		Tier:       "cma",
		Summary:    "List roles in a space",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("roles", "list", "List roles in a space", "/spaces/{space_id}/roles"),
	},
	{
		ID:         "roles.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/roles/{role_id}",
		Tier:       "cma",
		Summary:    "Update a role (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "role_id"},
		keywords:   codeOrchKeywords("roles", "update", "Update a role (requires X-Contentful-Version header)", "/spaces/{space_id}/roles/{role_id}"),
	},
	{
		ID:         "scheduled_actions.cancel",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/scheduled_actions/{scheduled_action_id}",
		Tier:       "cma",
		Summary:    "Cancel a scheduled action",
		Positional: []string{"space_id", "scheduled_action_id"},
		keywords:   codeOrchKeywords("scheduled_actions", "cancel", "Cancel a scheduled action", "/spaces/{space_id}/scheduled_actions/{scheduled_action_id}"),
	},
	{
		ID:         "scheduled_actions.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/scheduled_actions",
		Tier:       "cma",
		Summary:    "Schedule a publish or unpublish action",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("scheduled_actions", "create", "Schedule a publish or unpublish action", "/spaces/{space_id}/scheduled_actions"),
	},
	{
		ID:         "scheduled_actions.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/scheduled_actions/{scheduled_action_id}",
		Tier:       "cma",
		Summary:    "Get a scheduled action by ID",
		Positional: []string{"space_id", "scheduled_action_id"},
		keywords:   codeOrchKeywords("scheduled_actions", "get", "Get a scheduled action by ID", "/spaces/{space_id}/scheduled_actions/{scheduled_action_id}"),
	},
	{
		ID:         "scheduled_actions.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/scheduled_actions",
		Tier:       "cma",
		Summary:    "List scheduled actions",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("scheduled_actions", "list", "List scheduled actions", "/spaces/{space_id}/scheduled_actions"),
	},
	{
		ID:         "space_memberships.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/space_memberships",
		Tier:       "cma",
		Summary:    "List members of a space",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("space_memberships", "list", "List members of a space", "/spaces/{space_id}/space_memberships"),
	},
	{
		ID:         "spaces.create",
		Method:     "POST",
		Path:       "/spaces",
		Tier:       "cma",
		Summary:    "Create a new space",
		Positional: []string{},
		keywords:   codeOrchKeywords("spaces", "create", "Create a new space", "/spaces"),
	},
	{
		ID:         "spaces.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}",
		Tier:       "cma",
		Summary:    "Delete a space",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("spaces", "delete", "Delete a space", "/spaces/{space_id}"),
	},
	{
		ID:         "spaces.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}",
		Tier:       "cma",
		Summary:    "Get a space by ID",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("spaces", "get", "Get a space by ID", "/spaces/{space_id}"),
	},
	{
		ID:         "spaces.list",
		Method:     "GET",
		Path:       "/spaces",
		Tier:       "cma",
		Summary:    "List all spaces accessible to the token",
		Positional: []string{},
		keywords:   codeOrchKeywords("spaces", "list", "List all spaces accessible to the token", "/spaces"),
	},
	{
		ID:         "spaces.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}",
		Tier:       "cma",
		Summary:    "Update a space (requires X-Contentful-Version header)",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("spaces", "update", "Update a space (requires X-Contentful-Version header)", "/spaces/{space_id}"),
	},
	{
		ID:         "tags.create",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}",
		Tier:       "cma",
		Summary:    "Create a tag with the given ID",
		Positional: []string{"space_id", "environment_id", "tag_id"},
		keywords:   codeOrchKeywords("tags", "create", "Create a tag with the given ID", "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}"),
	},
	{
		ID:         "tags.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}",
		Tier:       "cma",
		Summary:    "Delete a tag",
		Positional: []string{"space_id", "environment_id", "tag_id"},
		keywords:   codeOrchKeywords("tags", "delete", "Delete a tag", "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}"),
	},
	{
		ID:         "tags.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}",
		Tier:       "cma",
		Summary:    "Get a tag by ID",
		Positional: []string{"space_id", "environment_id", "tag_id"},
		keywords:   codeOrchKeywords("tags", "get", "Get a tag by ID", "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}"),
	},
	{
		ID:         "tags.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/tags",
		Tier:       "cma",
		Summary:    "List tags in an environment",
		Positional: []string{"space_id", "environment_id"},
		keywords:   codeOrchKeywords("tags", "list", "List tags in an environment", "/spaces/{space_id}/environments/{environment_id}/tags"),
	},
	{
		ID:         "tags.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}",
		Tier:       "cma",
		Summary:    "Update a tag (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "tag_id"},
		keywords:   codeOrchKeywords("tags", "update", "Update a tag (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/tags/{tag_id}"),
	},
	{
		ID:         "tasks.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks",
		Tier:       "cma",
		Summary:    "Create a task on an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("tasks", "create", "Create a task on an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks"),
	},
	{
		ID:         "tasks.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}",
		Tier:       "cma",
		Summary:    "Delete a task",
		Positional: []string{"space_id", "environment_id", "entry_id", "task_id"},
		keywords:   codeOrchKeywords("tasks", "delete", "Delete a task", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}"),
	},
	{
		ID:         "tasks.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}",
		Tier:       "cma",
		Summary:    "Get a task by ID",
		Positional: []string{"space_id", "environment_id", "entry_id", "task_id"},
		keywords:   codeOrchKeywords("tasks", "get", "Get a task by ID", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}"),
	},
	{
		ID:         "tasks.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks",
		Tier:       "cma",
		Summary:    "List tasks on an entry",
		Positional: []string{"space_id", "environment_id", "entry_id"},
		keywords:   codeOrchKeywords("tasks", "list", "List tasks on an entry", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks"),
	},
	{
		ID:         "tasks.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}",
		Tier:       "cma",
		Summary:    "Update a task (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "environment_id", "entry_id", "task_id"},
		keywords:   codeOrchKeywords("tasks", "update", "Update a task (requires X-Contentful-Version header)", "/spaces/{space_id}/environments/{environment_id}/entries/{entry_id}/tasks/{task_id}"),
	},
	{
		ID:         "users.me",
		Method:     "GET",
		Path:       "/users/me",
		Tier:       "cma",
		Summary:    "Get the authenticated user's profile",
		Positional: []string{},
		keywords:   codeOrchKeywords("users", "me", "Get the authenticated user's profile", "/users/me"),
	},
	{
		ID:         "webhook_calls.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/webhooks/{webhook_id}/calls/{call_id}",
		Tier:       "cma",
		Summary:    "Get a single webhook call (full request/response)",
		Positional: []string{"space_id", "webhook_id", "call_id"},
		keywords:   codeOrchKeywords("webhook_calls", "get", "Get a single webhook call (full request/response)", "/spaces/{space_id}/webhooks/{webhook_id}/calls/{call_id}"),
	},
	{
		ID:         "webhook_calls.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/webhooks/{webhook_id}/calls",
		Tier:       "cma",
		Summary:    "List recent webhook calls (delivery log)",
		Positional: []string{"space_id", "webhook_id"},
		keywords:   codeOrchKeywords("webhook_calls", "list", "List recent webhook calls (delivery log)", "/spaces/{space_id}/webhooks/{webhook_id}/calls"),
	},
	{
		ID:         "webhooks.create",
		Method:     "POST",
		Path:       "/spaces/{space_id}/webhook_definitions",
		Tier:       "cma",
		Summary:    "Create a webhook definition",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("webhooks", "create", "Create a webhook definition", "/spaces/{space_id}/webhook_definitions"),
	},
	{
		ID:         "webhooks.delete",
		Method:     "DELETE",
		Path:       "/spaces/{space_id}/webhook_definitions/{webhook_id}",
		Tier:       "cma",
		Summary:    "Delete a webhook",
		Positional: []string{"space_id", "webhook_id"},
		keywords:   codeOrchKeywords("webhooks", "delete", "Delete a webhook", "/spaces/{space_id}/webhook_definitions/{webhook_id}"),
	},
	{
		ID:         "webhooks.get",
		Method:     "GET",
		Path:       "/spaces/{space_id}/webhook_definitions/{webhook_id}",
		Tier:       "cma",
		Summary:    "Get a webhook definition by ID",
		Positional: []string{"space_id", "webhook_id"},
		keywords:   codeOrchKeywords("webhooks", "get", "Get a webhook definition by ID", "/spaces/{space_id}/webhook_definitions/{webhook_id}"),
	},
	{
		ID:         "webhooks.health",
		Method:     "GET",
		Path:       "/spaces/{space_id}/webhooks/{webhook_id}/health",
		Tier:       "cma",
		Summary:    "Get a webhook's health (success/failure counts)",
		Positional: []string{"space_id", "webhook_id"},
		keywords:   codeOrchKeywords("webhooks", "health", "Get a webhook's health (success/failure counts)", "/spaces/{space_id}/webhooks/{webhook_id}/health"),
	},
	{
		ID:         "webhooks.list",
		Method:     "GET",
		Path:       "/spaces/{space_id}/webhook_definitions",
		Tier:       "cma",
		Summary:    "List webhook definitions",
		Positional: []string{"space_id"},
		keywords:   codeOrchKeywords("webhooks", "list", "List webhook definitions", "/spaces/{space_id}/webhook_definitions"),
	},
	{
		ID:         "webhooks.update",
		Method:     "PUT",
		Path:       "/spaces/{space_id}/webhook_definitions/{webhook_id}",
		Tier:       "cma",
		Summary:    "Update a webhook (requires X-Contentful-Version header)",
		Positional: []string{"space_id", "webhook_id"},
		keywords:   codeOrchKeywords("webhooks", "update", "Update a webhook (requires X-Contentful-Version header)", "/spaces/{space_id}/webhook_definitions/{webhook_id}"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"tier":        r.ep.Tier,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call contentful_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call contentful_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	c = c.WithTier(ep.Tier)

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[k] = fmt.Sprintf("%v", v)
		}
	}

	var data json.RawMessage
	switch ep.Method {
	case "GET":
		data, err = c.Get(path, query)
	case "DELETE":
		data, _, err = c.Delete(path)
	default:
		body, mErr := json.Marshal(params)
		if mErr != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("marshaling body: %v", mErr)), nil
		}
		switch ep.Method {
		case "POST":
			data, _, err = c.Post(path, body)
		case "PUT":
			data, _, err = c.Put(path, body)
		case "PATCH":
			data, _, err = c.Patch(path, body)
		default:
			return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
		}
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}
