// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"contentful-pp-cli/internal/cli"
	"contentful-pp-cli/internal/client"
	"contentful-pp-cli/internal/cliutil"
	"contentful-pp-cli/internal/config"
	"contentful-pp-cli/internal/mcp/cobratree"
	"contentful-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate, tier string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}
		c = c.WithTier(tier)

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export CONTENTFUL_MANAGEMENT_TOKEN=<your-key>" +
					"\n      Run 'contentful-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export CONTENTFUL_MANAGEMENT_TOKEN=<your-key>" +
					"\n      Run 'contentful-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export CONTENTFUL_MANAGEMENT_TOKEN=<your-key>" +
					"\n      Run 'contentful-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "contentful-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "contentful-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "contentful",
		"description": "Every Contentful API command, plus a local SQLite mirror that makes orphan detection, full environment diffs, and...",
		"archetype":   "content",
		"tool_count":  134,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion contentful-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "CONTENTFUL_MANAGEMENT_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"tier_routing": map[string]any{
			"default_tier": "cma",
			"tiers": map[string]any{
				"cda": map[string]any{
					"auth_type": "bearer_token",
					"base_url":  "https://cdn.contentful.com",
					"env_vars": []map[string]any{
						{
							"name":        "CONTENTFUL_DELIVERY_TOKEN",
							"kind":        "per_call",
							"required":    true,
							"sensitive":   true,
							"description": "Set to your API credential.",
						},
					},
				},
				"cma": map[string]any{
					"auth_type": "bearer_token",
					"env_vars": []map[string]any{
						{
							"name":        "CONTENTFUL_MANAGEMENT_TOKEN",
							"kind":        "per_call",
							"required":    true,
							"sensitive":   true,
							"description": "Set to your API credential.",
						},
					},
				},
				"cpa": map[string]any{
					"auth_type": "bearer_token",
					"base_url":  "https://preview.contentful.com",
					"env_vars": []map[string]any{
						{
							"name":        "CONTENTFUL_PREVIEW_TOKEN",
							"kind":        "per_call",
							"required":    true,
							"sensitive":   true,
							"description": "Set to your API credential.",
						},
					},
				},
				"gql": map[string]any{
					"auth_type": "bearer_token",
					"base_url":  "https://graphql.contentful.com",
					"env_vars": []map[string]any{
						{
							"name":        "CONTENTFUL_DELIVERY_TOKEN",
							"kind":        "per_call",
							"required":    true,
							"sensitive":   true,
							"description": "Set to your API credential.",
						},
					},
				},
			},
			"endpoints": map[string]string{
				"ai_actions_create":             "cma",
				"ai_actions_delete":             "cma",
				"ai_actions_get":                "cma",
				"ai_actions_invocation":         "cma",
				"ai_actions_invoke":             "cma",
				"ai_actions_list":               "cma",
				"ai_actions_publish":            "cma",
				"ai_actions_unpublish":          "cma",
				"ai_actions_update":             "cma",
				"api_keys_create":               "cma",
				"api_keys_delete":               "cma",
				"api_keys_get":                  "cma",
				"api_keys_list":                 "cma",
				"api_keys_update":               "cma",
				"app_installations_get":         "cma",
				"app_installations_install":     "cma",
				"app_installations_list":        "cma",
				"app_installations_uninstall":   "cma",
				"assets_archive":                "cma",
				"assets_create":                 "cma",
				"assets_delete":                 "cma",
				"assets_get":                    "cma",
				"assets_list":                   "cma",
				"assets_process":                "cma",
				"assets_publish":                "cma",
				"assets_unarchive":              "cma",
				"assets_unpublish":              "cma",
				"assets_update":                 "cma",
				"comments_create":               "cma",
				"comments_delete":               "cma",
				"comments_get":                  "cma",
				"comments_list":                 "cma",
				"comments_update":               "cma",
				"content_type_snapshots_get":    "cma",
				"content_type_snapshots_list":   "cma",
				"content_types_create":          "cma",
				"content_types_delete":          "cma",
				"content_types_get":             "cma",
				"content_types_list":            "cma",
				"content_types_publish":         "cma",
				"content_types_unpublish":       "cma",
				"content_types_update":          "cma",
				"delivery_assets_get":           "cda",
				"delivery_assets_list":          "cda",
				"delivery_content_types_get":    "cda",
				"delivery_content_types_list":   "cda",
				"delivery_entries_get":          "cda",
				"delivery_entries_list":         "cda",
				"delivery_locales_list":         "cda",
				"delivery_sync_run":             "cda",
				"editor_interfaces_get":         "cma",
				"editor_interfaces_list":        "cma",
				"editor_interfaces_update":      "cma",
				"entries_archive":               "cma",
				"entries_create":                "cma",
				"entries_delete":                "cma",
				"entries_get":                   "cma",
				"entries_list":                  "cma",
				"entries_publish":               "cma",
				"entries_references":            "cma",
				"entries_unarchive":             "cma",
				"entries_unpublish":             "cma",
				"entries_update":                "cma",
				"entry_snapshots_get":           "cma",
				"entry_snapshots_list":          "cma",
				"environment_aliases_get":       "cma",
				"environment_aliases_list":      "cma",
				"environment_aliases_update":    "cma",
				"environments_create":           "cma",
				"environments_delete":           "cma",
				"environments_get":              "cma",
				"environments_list":             "cma",
				"extensions_create":             "cma",
				"extensions_delete":             "cma",
				"extensions_get":                "cma",
				"extensions_list":               "cma",
				"extensions_update":             "cma",
				"gql_query":                     "gql",
				"locales_create":                "cma",
				"locales_delete":                "cma",
				"locales_get":                   "cma",
				"locales_list":                  "cma",
				"locales_update":                "cma",
				"organization_memberships_list": "cma",
				"organizations_get":             "cma",
				"organizations_list":            "cma",
				"preview_api_keys_get":          "cma",
				"preview_api_keys_list":         "cma",
				"preview_assets_get":            "cpa",
				"preview_assets_list":           "cpa",
				"preview_entries_get":           "cpa",
				"preview_entries_list":          "cpa",
				"release_actions_get":           "cma",
				"release_actions_list":          "cma",
				"releases_create":               "cma",
				"releases_delete":               "cma",
				"releases_get":                  "cma",
				"releases_list":                 "cma",
				"releases_publish":              "cma",
				"releases_update":               "cma",
				"roles_create":                  "cma",
				"roles_delete":                  "cma",
				"roles_get":                     "cma",
				"roles_list":                    "cma",
				"roles_update":                  "cma",
				"scheduled_actions_cancel":      "cma",
				"scheduled_actions_create":      "cma",
				"scheduled_actions_get":         "cma",
				"scheduled_actions_list":        "cma",
				"space_memberships_list":        "cma",
				"spaces_create":                 "cma",
				"spaces_delete":                 "cma",
				"spaces_get":                    "cma",
				"spaces_list":                   "cma",
				"spaces_update":                 "cma",
				"tags_create":                   "cma",
				"tags_delete":                   "cma",
				"tags_get":                      "cma",
				"tags_list":                     "cma",
				"tags_update":                   "cma",
				"tasks_create":                  "cma",
				"tasks_delete":                  "cma",
				"tasks_get":                     "cma",
				"tasks_list":                    "cma",
				"tasks_update":                  "cma",
				"users_me":                      "cma",
				"webhook_calls_get":             "cma",
				"webhook_calls_list":            "cma",
				"webhooks_create":               "cma",
				"webhooks_delete":               "cma",
				"webhooks_get":                  "cma",
				"webhooks_health":               "cma",
				"webhooks_list":                 "cma",
				"webhooks_update":               "cma",
			},
		},
		"resources": []map[string]any{
			{
				"name":        "ai_actions",
				"description": "Manage AI Actions (LLM-backed entry transformations) (CMA)",
				"endpoints":   []string{"create", "delete", "get", "invocation", "invoke", "list", "publish", "unpublish", "update"},
				"searchable":  true,
			},
			{
				"name":        "api_keys",
				"description": "Manage delivery API keys (CDA tokens) (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "app_installations",
				"description": "Manage app installations in an environment (CMA)",
				"endpoints":   []string{"get", "install", "list", "uninstall"},
				"searchable":  true,
			},
			{
				"name":        "assets",
				"description": "Manage assets (CMA)",
				"endpoints":   []string{"archive", "create", "delete", "get", "list", "process", "publish", "unarchive", "unpublish", "update"},
				"searchable":  true,
			},
			{
				"name":        "comments",
				"description": "Manage entry comments (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "content_type_snapshots",
				"description": "Read content type snapshots (history) (CMA)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "content_types",
				"description": "Manage content types (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "publish", "unpublish", "update"},
				"searchable":  true,
			},
			{
				"name":        "delivery_assets",
				"description": "Read published assets via the Content Delivery API (CDA tier)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "delivery_content_types",
				"description": "Read content types via the Content Delivery API (CDA tier)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "delivery_entries",
				"description": "Read published entries via the Content Delivery API (CDA tier — needs CONTENTFUL_DELIVERY_TOKEN)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "delivery_locales",
				"description": "Read locales via the Content Delivery API (CDA tier)",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "delivery_sync",
				"description": "CDA full + incremental sync (drives the local SQLite mirror) (CDA tier). Surfaced as 'delivery-sync' to avoid...",
				"endpoints":   []string{"run"},
				"searchable":  true,
			},
			{
				"name":        "editor_interfaces",
				"description": "Manage editor interfaces (Contentful UI controls per content type) (CMA)",
				"endpoints":   []string{"get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "entries",
				"description": "Manage entries (CMA)",
				"endpoints":   []string{"archive", "create", "delete", "get", "list", "publish", "references", "unarchive", "unpublish", "update"},
				"searchable":  true,
			},
			{
				"name":        "entry_snapshots",
				"description": "Read entry snapshots (history) (CMA)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "environment_aliases",
				"description": "Manage environment aliases (CMA)",
				"endpoints":   []string{"get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "environments",
				"description": "Manage environments within a space (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list"},
				"searchable":  true,
			},
			{
				"name":        "extensions",
				"description": "Manage UI extensions (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "gql",
				"description": "Execute GraphQL queries via the Contentful GraphQL Content API (gql tier)",
				"endpoints":   []string{"query"},
				"searchable":  true,
			},
			{
				"name":        "locales",
				"description": "Manage locales (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "organization_memberships",
				"description": "Read organization memberships (CMA)",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "organizations",
				"description": "Read organizations (CMA)",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "preview_api_keys",
				"description": "Read preview API keys (CPA tokens) (CMA)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "preview_assets",
				"description": "Read draft + published assets via the Content Preview API (CPA tier)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "preview_entries",
				"description": "Read draft + published entries via the Content Preview API (CPA tier — needs CONTENTFUL_PREVIEW_TOKEN)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "release_actions",
				"description": "Read async release actions (publish/validate job results) (CMA)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "releases",
				"description": "Manage releases (batched publish bundles) (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "publish", "update"},
				"searchable":  true,
			},
			{
				"name":        "roles",
				"description": "Manage roles (RBAC) (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "scheduled_actions",
				"description": "Manage scheduled actions (publish/unpublish at a future time) (CMA)",
				"endpoints":   []string{"cancel", "create", "get", "list"},
				"searchable":  true,
			},
			{
				"name":        "space_memberships",
				"description": "Read space memberships (CMA)",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "spaces",
				"description": "Manage Contentful spaces (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "tags",
				"description": "Manage tags (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "tasks",
				"description": "Manage entry tasks (workflow assignments) (CMA)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "Read user info (CMA)",
				"endpoints":   []string{"me"},
			},
			{
				"name":        "webhook_calls",
				"description": "Read webhook delivery logs (CMA)",
				"endpoints":   []string{"get", "list"},
				"searchable":  true,
			},
			{
				"name":        "webhooks",
				"description": "Manage webhooks (CMA)",
				"endpoints":   []string{"create", "delete", "get", "health", "list", "update"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Orphan detector", "command": "orphans", "description": "Find entries with no incoming references, content types with zero entries, and assets nobody links to — across the...", "rationale": "Requires graph traversal across the local SQLite mirror of entries, assets, and the references table; no single CMA...", "via": "mcp-command-mirror"},
			{"name": "Reference graph walker", "command": "refs", "description": "Walk the reference graph forward (what does this entry reference) and reverse (what references this entry) to any...", "rationale": "CMA's /references endpoint is depth-1 only and online; arbitrary-depth + reverse direction is a BFS over the local...", "via": "mcp-command-mirror"},
			{"name": "Full environment diff", "command": "diff", "description": "Diff two environments across entries, content types, releases, scheduled actions, tags, tasks, and roles — the...", "rationale": "Joins per-environment mirrors of every entity table; computes structural, content, and config deltas in one pass.", "via": "mcp-command-mirror"},
			{"name": "Migration generator", "command": "migrate-gen", "description": "Diff two environments and emit a runnable contentful-migration JS script. Inverts the painful 'make changes manually...", "rationale": "Reuses the diff engine and walks the structural deltas to emit createContentType / createField / transformEntries calls.", "via": "mcp-command-mirror"},
			{"name": "Field usage analyzer", "command": "field-usage", "description": "Per-locale fill rate for a field; distribution of value shapes; flags fields defined on a content type that no entry...", "rationale": "SQL aggregates over the entries JSON column grouped by content type and locale; only possible with a local mirror...", "via": "mcp-command-mirror"},
			{"name": "SQL-driven bulk operations", "command": "entries bulk", "description": "Use a SQL WHERE against the local mirror to pick which entries to publish, unpublish, or validate — with --dry-run...", "rationale": "Local SQL selects the targets; live run uses an adaptive token bucket against the CMA bulk-action endpoint.", "via": "mcp-command-mirror"},
			{"name": "Local content validation", "command": "validate-content", "description": "Run the content-type validations (regex, range, in, linkContentType) against the local entries mirror and report...", "rationale": "Walks local entries against locally-stored content-type validation rules; offline.", "via": "mcp-command-mirror"},
			{"name": "Broken-reference finder", "command": "refs-broken", "description": "Flags entries whose link fields point at deleted, archived, or unpublished targets — per locale, per environment.", "rationale": "LEFT JOIN against the references table with publish-state filter; pure local query.", "via": "mcp-command-mirror"},
			{"name": "Resumable rate-aware migrator", "command": "migrate run --resumable", "description": "Run a contentful-migration script with a local checkpoint table; reads X-Contentful-RateLimit-Reset to time backoff;...", "rationale": "Local migration_checkpoints table keyed on script-hash + entry-id; adaptive rate limiter uses the response headers.", "via": "mcp-command-mirror"},
			{"name": "GraphQL impact analyzer", "command": "gql-impact", "description": "Given a content-type field about to be removed, scan local .graphql/.ts/.tsx files in cwd for queries referencing it...", "rationale": "Joins the local content-type schema with cwd source files via AST search; cross-source.", "via": "mcp-command-mirror"},
			{"name": "Image URL builder with srcset", "command": "images url", "description": "Build images.ctfassets.net URLs with all transforms (w/h/fit/format/quality); --bulk for many assets; --srcset emits...", "rationale": "Pure URL construction; --bulk joins the local assets table for filename and token; --srcset templates HTML.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Orphan detector", "insight": "Requires graph traversal across the local SQLite mirror of entries, assets, and the references table; no single CMA endpoint answers this."},
			{"topic": "Reference graph walker", "insight": "CMA's /references endpoint is depth-1 only and online; arbitrary-depth + reverse direction is a BFS over the local references table."},
			{"topic": "Full environment diff", "insight": "Joins per-environment mirrors of every entity table; computes structural, content, and config deltas in one pass."},
			{"topic": "Migration generator", "insight": "Reuses the diff engine and walks the structural deltas to emit createContentType / createField / transformEntries calls."},
			{"topic": "Field usage analyzer", "insight": "SQL aggregates over the entries JSON column grouped by content type and locale; only possible with a local mirror plus the content-type schema joined."},
			{"topic": "SQL-driven bulk operations", "insight": "Local SQL selects the targets; live run uses an adaptive token bucket against the CMA bulk-action endpoint."},
			{"topic": "Local content validation", "insight": "Walks local entries against locally-stored content-type validation rules; offline."},
			{"topic": "Broken-reference finder", "insight": "LEFT JOIN against the references table with publish-state filter; pure local query."},
			{"topic": "Resumable rate-aware migrator", "insight": "Local migration_checkpoints table keyed on script-hash + entry-id; adaptive rate limiter uses the response headers."},
			{"topic": "GraphQL impact analyzer", "insight": "Joins the local content-type schema with cwd source files via AST search; cross-source."},
			{"topic": "Image URL builder with srcset", "insight": "Pure URL construction; --bulk joins the local assets table for filename and token; --srcset templates HTML."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
