// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAiActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ai-actions",
		Short: "Manage AI Actions (LLM-backed entry transformations) (CMA)",
	}

	cmd.AddCommand(newAiActionsCreateCmd(flags))
	cmd.AddCommand(newAiActionsDeleteCmd(flags))
	cmd.AddCommand(newAiActionsGetCmd(flags))
	cmd.AddCommand(newAiActionsInvocationCmd(flags))
	cmd.AddCommand(newAiActionsInvokeCmd(flags))
	cmd.AddCommand(newAiActionsListCmd(flags))
	cmd.AddCommand(newAiActionsPublishCmd(flags))
	cmd.AddCommand(newAiActionsUnpublishCmd(flags))
	cmd.AddCommand(newAiActionsUpdateCmd(flags))
	return cmd
}
