// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAiActionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyName string
	var bodyDescription string
	var bodyConfiguration string
	var bodyInstruction string
	var bodyTestCases string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <space_id> <environment_id>",
		Short:       "Create an AI Action",
		Example:     "  contentful-pp-cli ai-actions create 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "ai_actions.create", "pp:method": "POST", "pp:path": "/spaces/{space_id}/environments/{environment_id}/ai_actions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("configuration") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "configuration")
				}
				if !cmd.Flags().Changed("instruction") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "instruction")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("cma")

			path := "/spaces/{space_id}/environments/{environment_id}/ai_actions"
			path = replacePathParam(path, "space_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("environment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "environment_id"))
			}
			path = replacePathParam(path, "environment_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyConfiguration != "" {
					var parsedConfiguration any
					if err := json.Unmarshal([]byte(bodyConfiguration), &parsedConfiguration); err != nil {
						return fmt.Errorf("parsing --configuration JSON: %w", err)
					}
					body["configuration"] = bodyConfiguration
				}
				if bodyInstruction != "" {
					var parsedInstruction any
					if err := json.Unmarshal([]byte(bodyInstruction), &parsedInstruction); err != nil {
						return fmt.Errorf("parsing --instruction JSON: %w", err)
					}
					body["instruction"] = bodyInstruction
				}
				if bodyTestCases != "" {
					var parsedTestCases any
					if err := json.Unmarshal([]byte(bodyTestCases), &parsedTestCases); err != nil {
						return fmt.Errorf("parsing --test-cases JSON: %w", err)
					}
					body["testCases"] = bodyTestCases
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "ai_actions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "AI Action name")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "AI Action description")
	cmd.Flags().StringVar(&bodyConfiguration, "configuration", "", "Model configuration as JSON ({modelType, modelTemperature})")
	cmd.Flags().StringVar(&bodyInstruction, "instruction", "", "Instruction template (with {{variables}}) as JSON ({template, variables})")
	cmd.Flags().StringVar(&bodyTestCases, "test-cases", "", "Test cases as JSON array")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
