// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newApiKeysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "api-keys",
		Short: "Manage delivery API keys (CDA tokens) (CMA)",
	}

	cmd.AddCommand(newApiKeysCreateCmd(flags))
	cmd.AddCommand(newApiKeysDeleteCmd(flags))
	cmd.AddCommand(newApiKeysGetCmd(flags))
	cmd.AddCommand(newApiKeysListCmd(flags))
	cmd.AddCommand(newApiKeysUpdateCmd(flags))
	return cmd
}
