// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAppInstallationsGetCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:         "get <space_id> <environment_id> <app_definition_id>",
		Short:       "Get an app installation by app definition ID",
		Example:     "  contentful-pp-cli app-installations get 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "app_installations.get", "pp:method": "GET", "pp:path": "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("cma")

			path := "/spaces/{space_id}/environments/{environment_id}/app_installations/{app_definition_id}"
			path = replacePathParam(path, "space_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("environment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "environment_id"))
			}
			path = replacePathParam(path, "environment_id", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("app_definition_id is required\nUsage: %s <%s>", cmd.CommandPath(), "app_definition_id"))
			}
			path = replacePathParam(path, "app_definition_id", args[2])
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "app_installations", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	return cmd
}
