// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAppInstallationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "app-installations",
		Short: "Manage app installations in an environment (CMA)",
	}

	cmd.AddCommand(newAppInstallationsGetCmd(flags))
	cmd.AddCommand(newAppInstallationsInstallCmd(flags))
	cmd.AddCommand(newAppInstallationsListCmd(flags))
	cmd.AddCommand(newAppInstallationsUninstallCmd(flags))
	return cmd
}
