// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAssetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "assets",
		Short: "Manage assets (CMA)",
	}

	cmd.AddCommand(newAssetsArchiveCmd(flags))
	cmd.AddCommand(newAssetsCreateCmd(flags))
	cmd.AddCommand(newAssetsDeleteCmd(flags))
	cmd.AddCommand(newAssetsGetCmd(flags))
	cmd.AddCommand(newAssetsListCmd(flags))
	cmd.AddCommand(newAssetsProcessCmd(flags))
	cmd.AddCommand(newAssetsPublishCmd(flags))
	cmd.AddCommand(newAssetsUnarchiveCmd(flags))
	cmd.AddCommand(newAssetsUnpublishCmd(flags))
	cmd.AddCommand(newAssetsUpdateCmd(flags))
	return cmd
}
