// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCommentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "comments",
		Short: "Manage entry comments (CMA)",
	}

	cmd.AddCommand(newCommentsCreateCmd(flags))
	cmd.AddCommand(newCommentsDeleteCmd(flags))
	cmd.AddCommand(newCommentsGetCmd(flags))
	cmd.AddCommand(newCommentsListCmd(flags))
	cmd.AddCommand(newCommentsUpdateCmd(flags))
	return cmd
}
