// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentTypeSnapshotsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-type-snapshots",
		Short: "Read content type snapshots (history) (CMA)",
	}

	cmd.AddCommand(newContentTypeSnapshotsGetCmd(flags))
	cmd.AddCommand(newContentTypeSnapshotsListCmd(flags))
	return cmd
}
