// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "content-types",
		Short: "Manage content types (CMA)",
	}

	cmd.AddCommand(newContentTypesCreateCmd(flags))
	cmd.AddCommand(newContentTypesDeleteCmd(flags))
	cmd.AddCommand(newContentTypesGetCmd(flags))
	cmd.AddCommand(newContentTypesListCmd(flags))
	cmd.AddCommand(newContentTypesPublishCmd(flags))
	cmd.AddCommand(newContentTypesUnpublishCmd(flags))
	cmd.AddCommand(newContentTypesUpdateCmd(flags))
	return cmd
}
