// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDeliveryEntriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delivery-entries",
		Short: "Read published entries via the Content Delivery API (CDA tier — needs CONTENTFUL_DELIVERY_TOKEN)",
	}

	cmd.AddCommand(newDeliveryEntriesGetCmd(flags))
	cmd.AddCommand(newDeliveryEntriesListCmd(flags))
	return cmd
}
