// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDeliveryContentTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "delivery-content-types",
		Short: "Read content types via the Content Delivery API (CDA tier)",
	}

	cmd.AddCommand(newDeliveryContentTypesGetCmd(flags))
	cmd.AddCommand(newDeliveryContentTypesListCmd(flags))
	return cmd
}
