// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEntrySnapshotsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "entry-snapshots",
		Short: "Read entry snapshots (history) (CMA)",
	}

	cmd.AddCommand(newEntrySnapshotsGetCmd(flags))
	cmd.AddCommand(newEntrySnapshotsListCmd(flags))
	return cmd
}
