// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Originally generated by CLI Printing Press; hand-extended in Phase 3 to
// register the bulk-publish/bulk-unpublish/bulk-validate transcendence
// children inline so static parsers (verify-skill) can see them.

package cli

import (
	"github.com/spf13/cobra"
)

func newEntriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "entries",
		Short: "Manage entries (CMA)",
	}

	cmd.AddCommand(newEntriesArchiveCmd(flags))
	cmd.AddCommand(newEntriesCreateCmd(flags))
	cmd.AddCommand(newEntriesDeleteCmd(flags))
	cmd.AddCommand(newEntriesGetCmd(flags))
	cmd.AddCommand(newEntriesListCmd(flags))
	cmd.AddCommand(newEntriesPublishCmd(flags))
	cmd.AddCommand(newEntriesReferencesCmd(flags))
	cmd.AddCommand(newEntriesUnarchiveCmd(flags))
	cmd.AddCommand(newEntriesUnpublishCmd(flags))
	cmd.AddCommand(newEntriesUpdateCmd(flags))
	// Hand-authored Phase 3 transcendence children — see entries_bulk.go.
	cmd.AddCommand(newEntriesBulkPublishCmd(flags))
	cmd.AddCommand(newEntriesBulkUnpublishCmd(flags))
	cmd.AddCommand(newEntriesBulkValidateCmd(flags))
	return cmd
}
