// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEnvironmentAliasesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "environment-aliases",
		Short: "Manage environment aliases (CMA)",
	}

	cmd.AddCommand(newEnvironmentAliasesGetCmd(flags))
	cmd.AddCommand(newEnvironmentAliasesListCmd(flags))
	cmd.AddCommand(newEnvironmentAliasesUpdateCmd(flags))
	return cmd
}
