// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEnvironmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "environments",
		Short: "Manage environments within a space (CMA)",
	}

	cmd.AddCommand(newEnvironmentsCreateCmd(flags))
	cmd.AddCommand(newEnvironmentsDeleteCmd(flags))
	cmd.AddCommand(newEnvironmentsGetCmd(flags))
	cmd.AddCommand(newEnvironmentsListCmd(flags))
	return cmd
}
