// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLocalesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "locales",
		Short: "Manage locales (CMA)",
	}

	cmd.AddCommand(newLocalesCreateCmd(flags))
	cmd.AddCommand(newLocalesDeleteCmd(flags))
	cmd.AddCommand(newLocalesGetCmd(flags))
	cmd.AddCommand(newLocalesListCmd(flags))
	cmd.AddCommand(newLocalesUpdateCmd(flags))
	return cmd
}
