// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"contentful-pp-cli/internal/store"
	"github.com/spf13/cobra"
)

func newMigrateGenCmd(flags *rootFlags) *cobra.Command {
	var fromEnv, toEnv, output, dbPath string
	cmd := &cobra.Command{
		Use:   "migrate-gen",
		Short: "Generate a contentful-migration JS script that brings env A's content-type schema toward env B",
		Long: `Diff two synced environments and emit a runnable contentful-migration JS
script. The script is generated against env A as the starting state.

Run the generated script with:
  npx contentful-migration <output.js> -s $CONTENTFUL_SPACE_ID -e <env-a> -t $CONTENTFUL_MANAGEMENT_TOKEN

Unsupported diff types (release content, scheduled actions, taxonomies) are
emitted as JS comments noting the gap.`,
		Example:     "  contentful-pp-cli migrate-gen --from staging --to master --output migrations/sync-staging-to-master.js",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			if fromEnv == "" || toEnv == "" {
				return usageErr(fmt.Errorf("both --from and --to are required"))
			}

			path := dbPath
			if path == "" {
				path = defaultDBPath("contentful-pp-cli")
			}
			if !dbExists(path) {
				return fmt.Errorf("local store %s not found — run 'contentful-pp-cli sync' first", path)
			}
			st, err := store.OpenReadOnly(path)
			if err != nil {
				return fmt.Errorf("opening local store at %s: %w", path, err)
			}
			defer st.Close()

			ctsFrom, err := loadCTSchemasForEnv(st, fromEnv)
			if err != nil {
				return err
			}
			ctsTo, err := loadCTSchemasForEnv(st, toEnv)
			if err != nil {
				return err
			}

			var b strings.Builder
			fmt.Fprintf(&b, "// Generated by contentful-pp-cli migrate-gen on %s\n", time.Now().UTC().Format(time.RFC3339))
			fmt.Fprintf(&b, "// from: %s\n// to:   %s\n//\n", fromEnv, toEnv)
			fmt.Fprintln(&b, "// Run with: npx contentful-migration <this-file> -s $CONTENTFUL_SPACE_ID -e <env> -t $CONTENTFUL_MANAGEMENT_TOKEN")
			fmt.Fprintln(&b, "// Notes:")
			fmt.Fprintln(&b, "//   - Releases, scheduled actions, taxonomies, and entry-level content drift")
			fmt.Fprintln(&b, "//     are not expressible in contentful-migration; see comments below.")
			fmt.Fprintln(&b, "")
			fmt.Fprintln(&b, "module.exports = function(migration) {")

			// Added content types
			added := make([]string, 0)
			for id := range ctsTo {
				if _, ok := ctsFrom[id]; !ok {
					added = append(added, id)
				}
			}
			sort.Strings(added)
			for _, id := range added {
				ct := ctsTo[id]
				name := ct.rawName
				if name == "" {
					name = id
				}
				fmt.Fprintf(&b, "  // create content type %s\n", id)
				fmt.Fprintf(&b, "  const %s = migration.createContentType(%q)\n", jsIdent(id), id)
				fmt.Fprintf(&b, "    .name(%q)\n", name)
				if ct.rawDescription != "" {
					fmt.Fprintf(&b, "    .description(%q)\n", ct.rawDescription)
				}
				if ct.displayField != "" {
					fmt.Fprintf(&b, "    .displayField(%q);\n\n", ct.displayField)
				} else {
					fmt.Fprintln(&b, "    ;")
					fmt.Fprintln(&b)
				}
				for _, f := range ct.Fields {
					emitCreateField(&b, jsIdent(id), f)
				}
				fmt.Fprintln(&b)
			}

			// Removed content types
			for id := range ctsFrom {
				if _, ok := ctsTo[id]; !ok {
					fmt.Fprintf(&b, "  migration.deleteContentType(%q);\n", id)
				}
			}

			// Modified content types — diff fields
			for id, fromCT := range ctsFrom {
				toCT, ok := ctsTo[id]
				if !ok {
					continue
				}
				addedF, removedF := diffFieldSets(fromCT.Fields, toCT.Fields)
				if len(addedF) == 0 && len(removedF) == 0 {
					continue
				}
				fmt.Fprintf(&b, "  // edit existing content type %s\n", id)
				fmt.Fprintf(&b, "  const edit_%s = migration.editContentType(%q);\n", jsIdent(id), id)
				for _, f := range addedF {
					emitCreateField(&b, "edit_"+jsIdent(id), f)
				}
				for _, fid := range removedF {
					fmt.Fprintf(&b, "  edit_%s.deleteField(%q);\n", jsIdent(id), fid)
				}
				fmt.Fprintln(&b)
			}

			fmt.Fprintln(&b, "  // ---")
			fmt.Fprintln(&b, "  // The following surfaces are not expressible in contentful-migration v4:")
			fmt.Fprintln(&b, "  //   - releases & scheduled actions (entry-level publish workflow state)")
			fmt.Fprintln(&b, "  //   - taxonomies / tags differences")
			fmt.Fprintln(&b, "  //   - entry data drift (use contentful-merge for that)")
			fmt.Fprintln(&b, "  // For those, run 'contentful-pp-cli diff <from> <to>' and reconcile manually.")
			fmt.Fprintln(&b, "};")

			out := b.String()
			if output == "" {
				_, err := fmt.Fprint(cmd.OutOrStdout(), out)
				return err
			}
			if err := os.MkdirAll(parentDir(output), 0o755); err != nil {
				return fmt.Errorf("creating output directory: %w", err)
			}
			if err := os.WriteFile(output, []byte(out), 0o644); err != nil {
				return err
			}
			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"output": output,
					"bytes":  len(out),
					"added":  len(added),
					"from":   fromEnv,
					"to":     toEnv,
				}, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s (%d bytes)\nrun: npx contentful-migration %s -s $CONTENTFUL_SPACE_ID -e <env> -t $CONTENTFUL_MANAGEMENT_TOKEN\n", output, len(out), output)
			return nil
		},
	}
	cmd.Flags().StringVar(&fromEnv, "from", "", "Starting environment (required)")
	cmd.Flags().StringVar(&toEnv, "to", "", "Target environment (required)")
	cmd.Flags().StringVar(&output, "output", "", "Output path (default: stdout)")
	cmd.Flags().StringVar(&dbPath, "db", "", "Override local DB path")
	return cmd
}

type ctSchemaFull struct {
	ctSchema
	rawName        string
	rawDescription string
	displayField   string
}

func loadCTSchemasForEnv(st *store.Store, env string) (map[string]ctSchemaFull, error) {
	out := map[string]ctSchemaFull{}
	rows, err := st.Query(`SELECT id, data FROM content_types WHERE parent_id = ?`, env)
	if err != nil {
		// Fallback to all-rows scan if parent_id isn't populated yet.
		rows, err = st.Query(`SELECT id, data FROM content_types`)
		if err != nil {
			return out, nil
		}
	}
	defer rows.Close()
	for rows.Next() {
		var id string
		var raw []byte
		if err := rows.Scan(&id, &raw); err != nil {
			continue
		}
		var obj map[string]any
		if err := json.Unmarshal(raw, &obj); err != nil {
			continue
		}
		full := ctSchemaFull{
			ctSchema:       ctSchema{ID: id},
			rawName:        stringField(obj, "name"),
			rawDescription: stringField(obj, "description"),
			displayField:   stringField(obj, "displayField"),
		}
		for _, f := range coerceMapList(obj["fields"]) {
			fld := ctField{
				ID:       stringField(f, "id"),
				Type:     stringField(f, "type"),
				LinkType: stringField(f, "linkType"),
			}
			full.Fields = append(full.Fields, fld)
		}
		out[id] = full
	}
	return out, nil
}

func diffFieldSets(from, to []ctField) (added []ctField, removed []string) {
	fromIDs := map[string]ctField{}
	for _, f := range from {
		fromIDs[f.ID] = f
	}
	toIDs := map[string]ctField{}
	for _, f := range to {
		toIDs[f.ID] = f
	}
	for id, f := range toIDs {
		if _, ok := fromIDs[id]; !ok {
			added = append(added, f)
		}
	}
	for id := range fromIDs {
		if _, ok := toIDs[id]; !ok {
			removed = append(removed, id)
		}
	}
	sort.Slice(added, func(i, j int) bool { return added[i].ID < added[j].ID })
	sort.Strings(removed)
	return
}

func emitCreateField(b *strings.Builder, ctVar string, f ctField) {
	t := f.Type
	if t == "" {
		t = "Symbol"
	}
	fmt.Fprintf(b, "  %s.createField(%q)\n", ctVar, f.ID)
	fmt.Fprintf(b, "    .type(%q)\n", t)
	fmt.Fprintf(b, "    .name(%q)", f.ID)
	if f.LinkType != "" {
		fmt.Fprintf(b, "\n    .linkType(%q)", f.LinkType)
	}
	fmt.Fprintln(b, ";")
}

func jsIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_' || r == '$' {
			b.WriteRune(r)
		} else if r >= '0' && r <= '9' {
			if i == 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "_"
	}
	return b.String()
}

func parentDir(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[:i]
	}
	return "."
}
