// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrganizationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "organizations",
		Short: "Read organizations (CMA)",
	}

	cmd.AddCommand(newOrganizationsGetCmd(flags))
	cmd.AddCommand(newOrganizationsListCmd(flags))
	return cmd
}
