// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPreviewEntriesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "preview-entries",
		Short: "Read draft + published entries via the Content Preview API (CPA tier — needs CONTENTFUL_PREVIEW_TOKEN)",
	}

	cmd.AddCommand(newPreviewEntriesGetCmd(flags))
	cmd.AddCommand(newPreviewEntriesListCmd(flags))
	return cmd
}
