// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPreviewApiKeysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "preview-api-keys",
		Short: "Read preview API keys (CPA tokens) (CMA)",
	}

	cmd.AddCommand(newPreviewApiKeysGetCmd(flags))
	cmd.AddCommand(newPreviewApiKeysListCmd(flags))
	return cmd
}
