// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPreviewAssetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "preview-assets",
		Short: "Read draft + published assets via the Content Preview API (CPA tier)",
	}

	cmd.AddCommand(newPreviewAssetsGetCmd(flags))
	cmd.AddCommand(newPreviewAssetsListCmd(flags))
	return cmd
}
