// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDeliverySyncPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagInitial bool
	var flagSyncToken string
	var flagType string
	var flagContentType string
	var flagResolveLinks bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "delivery-sync <space_id> <environment_id>",
		Short:       "Full or incremental sync. Use --initial=true once, then --sync-token from the prior nextSyncToken.",
		Long:        "Shortcut for 'delivery_sync run'. Full or incremental sync. Use --initial=true once, then --sync-token from the prior nextSyncToken.",
		Example:     "  contentful-pp-cli delivery-sync 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "delivery_sync.run", "pp:method": "GET", "pp:path": "/spaces/{space_id}/environments/{environment_id}/sync", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("cda")

			path := "/spaces/{space_id}/environments/{environment_id}/sync"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "space_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "space_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("space_id is required\nUsage: %s <%s>", cmd.CommandPath(), "space_id"))
			}
			path = replacePathParam(path, "space_id", args[0])
			if len(args) < 2 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "environment_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "environment_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("environment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "environment_id"))
			}
			path = replacePathParam(path, "environment_id", args[1])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "delivery_sync", path, map[string]string{
				"initial":      fmt.Sprintf("%v", flagInitial),
				"sync_token":   fmt.Sprintf("%v", flagSyncToken),
				"type":         fmt.Sprintf("%v", flagType),
				"content_type": fmt.Sprintf("%v", flagContentType),
				"resolveLinks": fmt.Sprintf("%v", flagResolveLinks),
			}, nil, flagAll, "", "", "nextPageUrl")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&flagInitial, "initial", false, "Start a fresh full sync (cannot combine with sync_token)")
	cmd.Flags().StringVar(&flagSyncToken, "sync-token", "", "Previous nextSyncToken to resume incremental sync")
	cmd.Flags().StringVar(&flagType, "type", "", "Limit to a single entity type (Entry|Asset|Deletion|DeletedEntry|DeletedAsset)")
	cmd.Flags().StringVar(&flagContentType, "content-type", "", "Limit Entry sync to a specific content type")
	cmd.Flags().BoolVar(&flagResolveLinks, "resolve-links", true, "Resolve linked entries inline")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
