// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGqlPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyQuery string
	var bodyVariables string
	var bodyOperationName string

	cmd := &cobra.Command{
		Use:         "gql <space_id> <environment_id>",
		Short:       "Run a GraphQL query against a space+environment",
		Long:        "Shortcut for 'gql query'. Run a GraphQL query against a space+environment",
		Example:     "  contentful-pp-cli gql 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --query example-value",
		Annotations: map[string]string{"pp:endpoint": "gql.query", "pp:method": "POST", "pp:path": "/content/v1/spaces/{space_id}/environments/{environment_id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("query") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "query")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("gql")

			path := "/content/v1/spaces/{space_id}/environments/{environment_id}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "space_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "space_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("space_id is required\nUsage: %s <%s>", cmd.CommandPath(), "space_id"))
			}
			path = replacePathParam(path, "space_id", args[0])
			if len(args) < 2 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "environment_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "environment_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("environment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "environment_id"))
			}
			path = replacePathParam(path, "environment_id", args[1])
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyQuery != "" {
				body["query"] = bodyQuery
			}
			if bodyVariables != "" {
				var parsedVariables any
				if err := json.Unmarshal([]byte(bodyVariables), &parsedVariables); err != nil {
					return fmt.Errorf("parsing --variables JSON: %w", err)
				}
				body["variables"] = bodyVariables
			}
			if bodyOperationName != "" {
				body["operationName"] = bodyOperationName
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyQuery, "query", "", "GraphQL query string (use @file.graphql)")
	cmd.Flags().StringVar(&bodyVariables, "variables", "", "GraphQL variables as JSON string")
	cmd.Flags().StringVar(&bodyOperationName, "operation-name", "", "Operation name when query has multiple operations")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
