// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReleasesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "releases",
		Short: "Manage releases (batched publish bundles) (CMA)",
	}

	cmd.AddCommand(newReleasesCreateCmd(flags))
	cmd.AddCommand(newReleasesDeleteCmd(flags))
	cmd.AddCommand(newReleasesGetCmd(flags))
	cmd.AddCommand(newReleasesListCmd(flags))
	cmd.AddCommand(newReleasesPublishCmd(flags))
	cmd.AddCommand(newReleasesUpdateCmd(flags))
	return cmd
}
