// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReleaseActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "release-actions",
		Short: "Read async release actions (publish/validate job results) (CMA)",
	}

	cmd.AddCommand(newReleaseActionsGetCmd(flags))
	cmd.AddCommand(newReleaseActionsListCmd(flags))
	return cmd
}
