// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "roles",
		Short: "Manage roles (RBAC) (CMA)",
	}

	cmd.AddCommand(newRolesCreateCmd(flags))
	cmd.AddCommand(newRolesDeleteCmd(flags))
	cmd.AddCommand(newRolesGetCmd(flags))
	cmd.AddCommand(newRolesListCmd(flags))
	cmd.AddCommand(newRolesUpdateCmd(flags))
	return cmd
}
