// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"contentful-pp-cli/internal/client"
	"contentful-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

var version = "1.0.0"

// globalUnwrap mirrors flags.unwrap so package-level helpers (wrapWithProvenance)
// can honor it without taking *rootFlags. Set in PersistentPreRunE; read inside
// the wrap helper. Single-process CLI, so no synchronization is required.
var globalUnwrap bool

type rootFlags struct {
	asJSON        bool
	compact       bool
	csv           bool
	plain         bool
	quiet         bool
	dryRun        bool
	noCache       bool
	noInput       bool
	idempotent    bool
	ignoreMissing bool
	yes           bool
	agent         bool
	unwrap        bool
	selectFields  string
	configPath    string
	profileName   string
	deliverSpec   string
	timeout       time.Duration
	rateLimit     float64
	dataSource    string
	freshnessMeta any

	// deliverBuf captures command output when --deliver is set to a
	// non-stdout sink. Flushed to the sink after Execute returns.
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)

	err := rootCmd.Execute()
	if err != nil && strings.Contains(err.Error(), "unknown flag") {
		msg := err.Error()
		// Extract the flag name from the error message (e.g., "unknown flag: --foob")
		if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
			flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
			if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
				return fmt.Errorf("%w\nhint: did you mean --%s?", err, suggestion)
			}
		}
	}
	if err == nil && flags.deliverBuf != nil {
		if derr := Deliver(flags.deliverSink, flags.deliverBuf.Bytes(), flags.compact); derr != nil {
			fmt.Fprintf(os.Stderr, "warning: deliver to %s:%s failed: %v\n", flags.deliverSink.Scheme, flags.deliverSink.Target, derr)
			return derr
		}
	}
	return err
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "contentful-pp-cli",
		Short: `Contentful CLI — Every Contentful API command, plus a local SQLite mirror that makes orphan detection, full environment diffs, and SQL-d…`,
		Long: `Contentful CLI — Every Contentful API command, plus a local SQLite mirror that makes orphan detection, full environment diffs, and SQL-d…

Highlights (not in the official API docs):
  • orphans   Find entries with no incoming references, content types with zero entries, and assets nobody links to — across the entire space, in seconds.
  • refs   Walk the reference graph forward (what does this entry reference) and reverse (what references this entry) to any depth, offline.
  • diff   Diff two environments across entries, content types, releases, scheduled actions, tags, tasks, and roles — the surfaces contentful-merge skips.
  • migrate-gen   Diff two environments and emit a runnable contentful-migration JS script. Inverts the painful 'make changes manually then write a script that mimics them' workflow.
  • field-usage   Per-locale fill rate for a field; distribution of value shapes; flags fields defined on a content type that no entry uses.
  • entries bulk-publish   Use a SQL WHERE against the local mirror to pick which entries to publish, unpublish, or validate — with --dry-run for safety and rate-aware execution that respects X-Contentful-RateLimit-* headers.
  • validate-content   Run the content-type validations (regex, range, in, linkContentType) against the local entries mirror and report violations — no API calls.
  • refs-broken   Flags entries whose link fields point at deleted, archived, or unpublished targets — per locale, per environment.
  • migrate run --resumable   Run a contentful-migration script with a local checkpoint table; reads X-Contentful-RateLimit-Reset to time backoff; resumes on crash without re-running completed entries.
  • gql-impact   Given a content-type field about to be removed, scan local .graphql/.ts/.tsx files in cwd for queries referencing it and print file:line.
  • images url   Build images.ctfassets.net URLs with all transforms (w/h/fit/format/quality); --bulk for many assets; --srcset emits ready-to-paste HTML.

Agent mode: add --agent to any command for JSON output + non-interactive mode.
Health check: run 'contentful-pp-cli doctor' to verify auth and connectivity.
See README.md or the bundled SKILL.md for recipes.`,
		SilenceUsage: true,
		Version:      version,
	}
	rootCmd.SetVersionTemplate("contentful-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 30*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noCache, "no-cache", false, "Bypass response cache")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().BoolVar(&flags.idempotent, "idempotent", false, "Treat already-existing create results as a successful no-op")
	rootCmd.PersistentFlags().BoolVar(&flags.ignoreMissing, "ignore-missing", false, "Treat missing delete targets as a successful no-op")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output (e.g. --select id,name,status)")
	rootCmd.PersistentFlags().BoolVar(&flags.unwrap, "unwrap", false, "Strip the {meta, results} envelope and the Contentful list wrapper; emit just the items array (or single object)")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (for agents and scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set all agent-friendly defaults (--json --compact --unwrap --no-input --no-color --yes)")
	rootCmd.PersistentFlags().StringVar(&flags.dataSource, "data-source", "auto", "Data source for read commands: auto (live with local fallback), live (API only), local (synced data only)")
	rootCmd.PersistentFlags().StringVar(&flags.profileName, "profile", "", "Apply values from a saved profile (see 'contentful-pp-cli profile list')")
	rootCmd.PersistentFlags().StringVar(&flags.deliverSpec, "deliver", "", "Route output to a sink: stdout (default), file:<path>, webhook:<url>")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", 0, "Max requests per second (0 to disable)")

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if flags.deliverSpec != "" {
			sink, err := ParseDeliverSink(flags.deliverSpec)
			if err != nil {
				return err
			}
			flags.deliverSink = sink
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				flags.deliverBuf = &bytes.Buffer{}
				cmd.SetOut(io.MultiWriter(os.Stdout, flags.deliverBuf))
			}
		}
		if flags.profileName != "" {
			profile, err := GetProfile(flags.profileName)
			if err != nil {
				return err
			}
			if profile == nil {
				available := ListProfileNames()
				if len(available) == 0 {
					return fmt.Errorf("profile %q not found (no profiles saved yet; run '%s profile save <name> --<flag> <value>')", flags.profileName, cmd.Root().Name())
				}
				return fmt.Errorf("profile %q not found; available: %s", flags.profileName, strings.Join(available, ", "))
			}
			if err := ApplyProfileToFlags(cmd, profile); err != nil {
				return err
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("yes") {
				flags.yes = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
			// --agent implies --unwrap by default: strip the provenance + list
			// envelopes so callers get a flat array (or single object). This is
			// the highest-leverage agent UX change — turns ~8-turn responses
			// into 1-2 turns. Pass --unwrap=false to opt out.
			if !cmd.Flags().Changed("unwrap") {
				flags.unwrap = true
			}
		}
		// Mirror to package-level so output helpers (which don't take *rootFlags)
		// can honor --unwrap without touching every list command's call site.
		globalUnwrap = flags.unwrap
		switch flags.dataSource {
		case "auto", "live", "local":
			// valid
		default:
			return fmt.Errorf("invalid --data-source value %q: must be auto, live, or local", flags.dataSource)
		}
		return nil
	}
	rootCmd.AddCommand(newAiActionsCmd(flags))
	rootCmd.AddCommand(newApiKeysCmd(flags))
	rootCmd.AddCommand(newAppInstallationsCmd(flags))
	rootCmd.AddCommand(newAssetsCmd(flags))
	rootCmd.AddCommand(newCommentsCmd(flags))
	rootCmd.AddCommand(newContentTypeSnapshotsCmd(flags))
	rootCmd.AddCommand(newContentTypesCmd(flags))
	rootCmd.AddCommand(newDeliveryAssetsCmd(flags))
	rootCmd.AddCommand(newDeliveryContentTypesCmd(flags))
	rootCmd.AddCommand(newDeliveryEntriesCmd(flags))
	rootCmd.AddCommand(newEditorInterfacesCmd(flags))
	// entries' bulk-publish/bulk-unpublish/bulk-validate children are now
	// registered directly inside newEntriesCmd (entries.go) so static parsers
	// like verify-skill can see them. attachEntriesBulkCmd is retained as a
	// no-op for backwards compat with any out-of-tree caller.
	rootCmd.AddCommand(newEntriesCmd(flags))
	rootCmd.AddCommand(newEntrySnapshotsCmd(flags))
	rootCmd.AddCommand(newEnvironmentAliasesCmd(flags))
	rootCmd.AddCommand(newEnvironmentsCmd(flags))
	rootCmd.AddCommand(newExtensionsCmd(flags))
	rootCmd.AddCommand(newLocalesCmd(flags))
	rootCmd.AddCommand(newOrganizationsCmd(flags))
	rootCmd.AddCommand(newPreviewApiKeysCmd(flags))
	rootCmd.AddCommand(newPreviewAssetsCmd(flags))
	rootCmd.AddCommand(newPreviewEntriesCmd(flags))
	rootCmd.AddCommand(newReleaseActionsCmd(flags))
	rootCmd.AddCommand(newReleasesCmd(flags))
	rootCmd.AddCommand(newRolesCmd(flags))
	rootCmd.AddCommand(newScheduledActionsCmd(flags))
	rootCmd.AddCommand(newSpacesCmd(flags))
	rootCmd.AddCommand(newTagsCmd(flags))
	rootCmd.AddCommand(newTasksCmd(flags))
	rootCmd.AddCommand(newWebhookCallsCmd(flags))
	rootCmd.AddCommand(newWebhooksCmd(flags))
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newAuthCmd(flags))
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	rootCmd.AddCommand(newProfileCmd(flags))
	rootCmd.AddCommand(newFeedbackCmd(flags))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newExportCmd(flags))
	rootCmd.AddCommand(newImportCmd(flags))
	rootCmd.AddCommand(newSearchCmd(flags))
	rootCmd.AddCommand(newSyncCmd(flags))
	rootCmd.AddCommand(newTailCmd(flags))
	rootCmd.AddCommand(newAnalyticsCmd(flags))
	rootCmd.AddCommand(newWorkflowCmd(flags))
	rootCmd.AddCommand(newAPICmd(flags))
	rootCmd.AddCommand(newDeliveryLocalesPromotedCmd(flags))
	rootCmd.AddCommand(newDeliverySyncPromotedCmd(flags))
	rootCmd.AddCommand(newGqlPromotedCmd(flags))
	rootCmd.AddCommand(newOrganizationMembershipsPromotedCmd(flags))
	rootCmd.AddCommand(newSpaceMembershipsPromotedCmd(flags))
	rootCmd.AddCommand(newUsersPromotedCmd(flags))
	// Hand-authored novel features (Phase 3 transcendence)
	rootCmd.AddCommand(newOrphansCmd(flags))
	rootCmd.AddCommand(newRefsCmd(flags))
	rootCmd.AddCommand(newRefsBrokenCmd(flags))
	rootCmd.AddCommand(newFieldUsageCmd(flags))
	rootCmd.AddCommand(newValidateContentCmd(flags))
	rootCmd.AddCommand(newDiffCmd(flags))
	rootCmd.AddCommand(newMigrateGenCmd(flags))
	rootCmd.AddCommand(newMigrateCmd(flags))
	rootCmd.AddCommand(newGqlImpactCmd(flags))
	rootCmd.AddCommand(newImagesCmd(flags))
	rootCmd.AddCommand(newVersionCliCmd())

	return rootCmd
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout, f.rateLimit)
	c.DryRun = f.dryRun
	c.NoCache = f.noCache
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	enc := json.NewEncoder(w.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}

func newVersionCliCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("contentful-pp-cli %s\n", version)
		},
	}
}
