// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newScheduledActionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "scheduled-actions",
		Short: "Manage scheduled actions (publish/unpublish at a future time) (CMA)",
	}

	cmd.AddCommand(newScheduledActionsCancelCmd(flags))
	cmd.AddCommand(newScheduledActionsCreateCmd(flags))
	cmd.AddCommand(newScheduledActionsGetCmd(flags))
	cmd.AddCommand(newScheduledActionsListCmd(flags))
	return cmd
}
