// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newScheduledActionsListCmd(flags *rootFlags) *cobra.Command {
	var flagEnvironmentSysId string
	var flagLimit int
	var flagOrder string

	cmd := &cobra.Command{
		Use:         "list <space_id>",
		Short:       "List scheduled actions",
		Example:     "  contentful-pp-cli scheduled-actions list 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "scheduled_actions.list", "pp:method": "GET", "pp:path": "/spaces/{space_id}/scheduled_actions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("cma")

			path := "/spaces/{space_id}/scheduled_actions"
			path = replacePathParam(path, "space_id", args[0])
			params := map[string]string{}
			if flagEnvironmentSysId != "" {
				params["environment.sys.id"] = fmt.Sprintf("%v", flagEnvironmentSysId)
			}
			if flagLimit != 0 {
				params["limit"] = fmt.Sprintf("%v", flagLimit)
			}
			if flagOrder != "" {
				params["order"] = fmt.Sprintf("%v", flagOrder)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "scheduled_actions", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Honor --limit when the API accepts but ignores ?limit=N.
			data = truncateJSONArray(data, flagLimit)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEnvironmentSysId, "environment-id", "", "Filter by environment ID (required by API)")
	cmd.Flags().IntVar(&flagLimit, "limit", 100, "Max results")
	cmd.Flags().StringVar(&flagOrder, "order", "", "Order by field (e.g., scheduledFor.datetime)")

	return cmd
}
