// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newScheduledActionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyEntitySysId string
	var bodyEntitySysLinkType string
	var bodyAction string
	var bodyScheduledForDatetime string
	var bodyEnvironmentSysId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <space_id>",
		Short:       "Schedule a publish or unpublish action",
		Example:     "  contentful-pp-cli scheduled-actions create 550e8400-e29b-41d4-a716-446655440000 --entity-sys-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "scheduled_actions.create", "pp:method": "POST", "pp:path": "/spaces/{space_id}/scheduled_actions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("entity-sys-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "entity-sys-id")
				}
				if !cmd.Flags().Changed("entity-sys-link-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "entity-sys-link-type")
				}
				if !cmd.Flags().Changed("action") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "action")
				}
				if !cmd.Flags().Changed("scheduled-for-datetime") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "scheduled-for-datetime")
				}
				if !cmd.Flags().Changed("environment-sys-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "environment-sys-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c = c.WithTier("cma")

			path := "/spaces/{space_id}/scheduled_actions"
			path = replacePathParam(path, "space_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyEntitySysId != "" {
					body["entity.sys.id"] = bodyEntitySysId
				}
				if bodyEntitySysLinkType != "" {
					body["entity.sys.linkType"] = bodyEntitySysLinkType
				}
				if bodyAction != "" {
					body["action"] = bodyAction
				}
				if bodyScheduledForDatetime != "" {
					body["scheduledFor.datetime"] = bodyScheduledForDatetime
				}
				if bodyEnvironmentSysId != "" {
					body["environment.sys.id"] = bodyEnvironmentSysId
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "scheduled_actions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyEntitySysId, "entity-sys-id", "", "Entity ID to schedule")
	cmd.Flags().StringVar(&bodyEntitySysLinkType, "entity-sys-link-type", "", "Entity type (Entry | Asset | Release)")
	cmd.Flags().StringVar(&bodyAction, "action", "", "Action to schedule")
	cmd.Flags().StringVar(&bodyScheduledForDatetime, "scheduled-for-datetime", "", "ISO 8601 datetime to run the action")
	cmd.Flags().StringVar(&bodyEnvironmentSysId, "environment-sys-id", "", "Environment ID where the action will run")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
