// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSpacesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "spaces",
		Short: "Manage Contentful spaces (CMA)",
	}

	cmd.AddCommand(newSpacesCreateCmd(flags))
	cmd.AddCommand(newSpacesDeleteCmd(flags))
	cmd.AddCommand(newSpacesGetCmd(flags))
	cmd.AddCommand(newSpacesListCmd(flags))
	cmd.AddCommand(newSpacesUpdateCmd(flags))
	return cmd
}
