// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhookCallsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "webhook-calls",
		Short: "Read webhook delivery logs (CMA)",
	}

	cmd.AddCommand(newWebhookCallsGetCmd(flags))
	cmd.AddCommand(newWebhookCallsListCmd(flags))
	return cmd
}
