// Copyright 2026 user. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	"path/filepath"
	"sync"
	"testing"
	"time"

	_ "modernc.org/sqlite"
)

// TestSchemaVersion_StampedOnFreshDB verifies that opening a brand-new
// database stamps the current schema version. This is the contract that
// makes StoreSchemaVersion upgrades safe: every freshly-created DB
// records the version it was built under.
func TestSchemaVersion_StampedOnFreshDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open fresh db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("fresh db version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_StampExistingZeroDB verifies the stamp-and-continue
// rule for existing deployed databases. A DB that predates the gate has
// user_version = 0; opening it with this binary should stamp the version
// to 1 without touching any data.
func TestSchemaVersion_StampExistingZeroDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with user_version = 0 and no tables, simulating
	// a database created by a pre-gate version of the binary before any
	// migrations ran.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 0`); err != nil {
		t.Fatalf("stamp zero: %v", err)
	}
	raw.Close()

	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open pre-gate db: %v", err)
	}
	defer s.Close()

	v, err := s.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("post-stamp version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestSchemaVersion_RefusesNewerDB verifies fail-fast when the on-disk
// schema is newer than the binary supports. Without this gate, a user
// who upgrades their library but not their binary would hit silent
// "no such column" errors instead of a clear version mismatch.
func TestSchemaVersion_RefusesNewerDB(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	_, err = Open(dbPath)
	if err == nil {
		t.Fatalf("expected open to fail on newer schema, got nil")
	}
}

// TestMigrate_ConcurrentFreshDB exercises the BEGIN IMMEDIATE migration
// transaction. Without it, N goroutines opening the same fresh DB in
// parallel race per CREATE TABLE statement and trip SQLITE_BUSY despite
// the busy_timeout. With it, they serialize on the RESERVED lock
// acquired at BEGIN time and every Open succeeds.
func TestMigrate_ConcurrentFreshDB(t *testing.T) {
	if testing.Short() {
		t.Skip("concurrent migration test can take up to migrationLockTimeout under contention")
	}
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	const n = 8
	errs := make(chan error, n)
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func() {
			defer wg.Done()
			s, err := Open(dbPath)
			if err != nil {
				errs <- err
				return
			}
			s.Close()
		}()
	}
	wg.Wait()
	close(errs)

	for err := range errs {
		t.Fatalf("concurrent Open failed: %v", err)
	}
}

// holdWriteLock takes an exclusive write lock on dbPath that a peer's
// BEGIN IMMEDIATE cannot acquire until the returned cleanup runs. Used
// to construct contention scenarios in the migration tests.
func holdWriteLock(t *testing.T, dbPath string) (cleanup func()) {
	t.Helper()
	holder, err := sql.Open("sqlite", dbPath+"?_journal_mode=WAL&_busy_timeout=5000")
	if err != nil {
		t.Fatalf("open holder: %v", err)
	}
	htx, err := holder.Begin()
	if err != nil {
		_ = holder.Close()
		t.Fatalf("begin holder tx: %v", err)
	}
	if _, err := htx.Exec(`CREATE TABLE IF NOT EXISTS holder_lock (id INTEGER)`); err != nil {
		_ = htx.Rollback()
		_ = holder.Close()
		t.Fatalf("seed holder write: %v", err)
	}
	return func() {
		_ = htx.Rollback()
		_ = holder.Close()
	}
}

// TestOpenWithContext_RespectsCancellation verifies that a caller that
// cancels its context during a stalled migration sees the cancellation
// surface as the returned error within a short window, instead of
// having to wait out the full migrationLockTimeout. SIGINT in a Cobra
// command's context must interrupt store.Open, not just block on it.
func TestOpenWithContext_RespectsCancellation(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")
	defer holdWriteLock(t, dbPath)()

	// Pre-cancel the context. The migration's BEGIN IMMEDIATE will BUSY
	// against the holder; the very first iteration of retryOnBusy then
	// hits the ctx.Done() arm of its select and propagates ctx.Canceled.
	// A blocked-then-cancel pattern using time.Sleep would prove the
	// same property but cost the sleep interval on every CI run.
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	start := time.Now()
	_, err := OpenWithContext(ctx, dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected OpenWithContext to fail under contention with cancelled ctx")
	}
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("expected context.Canceled in error chain, got: %v", err)
	}
	// Without ctx threading this would block until migrationLockTimeout
	// (default 30s). 5s is generous headroom over the actual return
	// time (microseconds for a pre-cancelled ctx) without flaking CI.
	if elapsed > 5*time.Second {
		t.Fatalf("OpenWithContext returned after %s; pre-cancelled ctx should short-circuit immediately", elapsed)
	}
}

// TestMigrate_RejectsNewerDBImmediately verifies that an old binary
// opening a newer-schema DB rejects fast even when a peer migrator is
// still holding the write lock. The schema-version check runs on the
// pinned connection BEFORE BEGIN IMMEDIATE so the rejection path
// doesn't have to wait out the migration lock.
func TestMigrate_RejectsNewerDBImmediately(t *testing.T) {
	t.Parallel()

	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-stamp the DB at a version this binary doesn't support.
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`PRAGMA user_version = 999`); err != nil {
		t.Fatalf("stamp future version: %v", err)
	}
	raw.Close()

	defer holdWriteLock(t, dbPath)()

	start := time.Now()
	_, err = Open(dbPath)
	elapsed := time.Since(start)

	if err == nil {
		t.Fatalf("expected Open to refuse a newer-schema DB")
	}
	// The fast-path goal: rejection must arrive well under
	// migrationLockTimeout. 5s leaves headroom over the WAL init race
	// (a few ms in practice) without being so tight CI flakes.
	if elapsed > 5*time.Second {
		t.Fatalf("Open rejected after %s; fast-path should reject in well under migrationLockTimeout (30s)", elapsed)
	}
}

// TestSchemaVersion_ReopenIsIdempotent verifies that opening an already
// correctly-stamped DB is a no-op — the second open reads the version
// and the migrations are all idempotent (CREATE TABLE IF NOT EXISTS).
func TestSchemaVersion_ReopenIsIdempotent(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	s1, err := Open(dbPath)
	if err != nil {
		t.Fatalf("first open: %v", err)
	}
	s1.Close()

	s2, err := Open(dbPath)
	if err != nil {
		t.Fatalf("second open: %v", err)
	}
	defer s2.Close()

	v, err := s2.SchemaVersion()
	if err != nil {
		t.Fatalf("read schema version: %v", err)
	}
	if v != StoreSchemaVersion {
		t.Fatalf("reopened version = %d, want %d", v, StoreSchemaVersion)
	}
}

// TestOpenReadOnly_RejectsWrites pins the contract: direct and CTE-wrapped
// writes against the main DB fail under mode=ro. Deliberately does not
// assert VACUUM INTO and ATTACH DATABASE — modernc.org/sqlite allows both
// under mode=ro, so those defenses live in the handleSQL keyword blocklist.
func TestOpenReadOnly_RejectsWrites(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	rw, err := Open(dbPath)
	if err != nil {
		t.Fatalf("seed open: %v", err)
	}
	if _, err := rw.DB().Exec(`INSERT INTO resources (id, resource_type, data) VALUES ('seed', 'thing', '{}')`); err != nil {
		t.Fatalf("seed insert: %v", err)
	}
	rw.Close()

	ro, err := OpenReadOnly(dbPath)
	if err != nil {
		t.Fatalf("open read-only: %v", err)
	}
	defer ro.Close()

	writes := []struct {
		name string
		stmt string
	}{
		{"insert", `INSERT INTO resources (id, resource_type, data) VALUES ('x', 'y', '{}')`},
		{"update", `UPDATE resources SET resource_type = 'hijacked' WHERE id = 'seed'`},
		{"delete", `DELETE FROM resources WHERE id = 'seed'`},
		{"replace", `REPLACE INTO resources (id, resource_type, data) VALUES ('seed', 'evil', '{}')`},
		// CTE-wrapped INSERT is load-bearing: it justifies leaving WITH
		// out of the handleSQL blocklist so SELECT-form CTEs work.
		{"cte_insert", `WITH stale AS (SELECT id FROM resources) INSERT INTO resources (id, resource_type, data) SELECT id || '-evil', 'thing', '{}' FROM stale`},
	}
	for _, w := range writes {
		if _, err := ro.DB().Exec(w.stmt); err == nil {
			t.Errorf("%s succeeded under mode=ro; expected rejection. stmt=%q", w.name, w.stmt)
		}
	}

	var count int
	if err := ro.DB().QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&count); err != nil {
		t.Fatalf("read-only SELECT failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("SELECT returned %d rows, want 1 (only the seed should remain)", count)
	}
	if err := ro.DB().QueryRow(`WITH r AS (SELECT id FROM resources WHERE id = 'seed') SELECT COUNT(*) FROM r`).Scan(&count); err != nil {
		t.Fatalf("read-only WITH...SELECT CTE failed: %v", err)
	}
	if count != 1 {
		t.Fatalf("CTE SELECT returned %d rows, want 1", count)
	}
}

// TestMigrate_AddsColumnsOnUpgrade_AiActions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_AiActions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE ai_actions (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(ai_actions)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"configuration",
		"instruction",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from ai_actions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ApiKeys verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ApiKeys(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE api_keys (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(api_keys)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"access_token",
		"environments",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from api_keys after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_AppInstallations verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_AppInstallations(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE app_installations (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(app_installations)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"parameters",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from app_installations after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Assets verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Assets(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE assets (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(assets)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from assets after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Comments verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Comments(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE comments (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(comments)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"body",
		"status",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from comments after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ContentTypeSnapshots verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ContentTypeSnapshots(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE content_type_snapshots (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(content_type_snapshots)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"snapshot",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from content_type_snapshots after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ContentTypes verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ContentTypes(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE content_types (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(content_types)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"display_field",
		"fields",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from content_types after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DeliveryAssets verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DeliveryAssets(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE delivery_assets (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(delivery_assets)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from delivery_assets after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DeliveryContentTypes verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DeliveryContentTypes(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE delivery_content_types (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(delivery_content_types)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"display_field",
		"fields",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from delivery_content_types after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DeliveryEntries verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DeliveryEntries(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE delivery_entries (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(delivery_entries)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"metadata",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from delivery_entries after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DeliveryLocales verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DeliveryLocales(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE delivery_locales (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(delivery_locales)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"code",
		"fallback_code",
		"default",
		"optional",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from delivery_locales after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_DeliverySync verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_DeliverySync(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE delivery_sync (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(delivery_sync)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from delivery_sync after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_EditorInterfaces verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_EditorInterfaces(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE editor_interfaces (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(editor_interfaces)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"controls",
		"sidebar",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from editor_interfaces after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Entries verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Entries(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE entries (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(entries)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"metadata",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from entries after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_EntrySnapshots verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_EntrySnapshots(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE entry_snapshots (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(entry_snapshots)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"snapshot",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from entry_snapshots after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_EnvironmentAliases verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_EnvironmentAliases(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE environment_aliases (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(environment_aliases)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"environment",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from environment_aliases after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Environments verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Environments(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE environments (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(environments)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from environments after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Extensions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Extensions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE extensions (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(extensions)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"extension",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from extensions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Locales verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Locales(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE locales (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(locales)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"code",
		"fallback_code",
		"default",
		"optional",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from locales after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_OrganizationMemberships verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_OrganizationMemberships(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE organization_memberships (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(organization_memberships)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from organization_memberships after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Organizations verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Organizations(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE organizations (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(organizations)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from organizations after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_PreviewApiKeys verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_PreviewApiKeys(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE preview_api_keys (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(preview_api_keys)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"access_token",
		"environments",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from preview_api_keys after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_PreviewAssets verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_PreviewAssets(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE preview_assets (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(preview_assets)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from preview_assets after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_PreviewEntries verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_PreviewEntries(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE preview_entries (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(preview_entries)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"fields",
		"metadata",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from preview_entries after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ReleaseActions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ReleaseActions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE release_actions (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(release_actions)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"entity",
		"action",
		"scheduled_for",
		"status",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from release_actions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Releases verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Releases(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE releases (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(releases)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"title",
		"entities",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from releases after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Roles verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Roles(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE roles (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(roles)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"description",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from roles after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_ScheduledActions verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_ScheduledActions(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE scheduled_actions (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(scheduled_actions)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"entity",
		"action",
		"scheduled_for",
		"status",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from scheduled_actions after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_SpaceMemberships verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_SpaceMemberships(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE space_memberships (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(space_memberships)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from space_memberships after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Spaces verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Spaces(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE spaces (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(spaces)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from spaces after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Tags verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Tags(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE tags (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(tags)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from tags after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Tasks verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Tasks(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE tasks (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(tasks)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"body",
		"assigned_to",
		"status",
		"due_date",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from tasks after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Users verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Users(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE users (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(users)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"first_name",
		"last_name",
		"email",
		"avatar_url",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from users after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_WebhookCalls verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_WebhookCalls(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE webhook_calls (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(webhook_calls)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"request",
		"response",
		"status_code",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from webhook_calls after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_Webhooks verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_Webhooks(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE webhooks (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(webhooks)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"name",
		"url",
		"topics",
		"http_basic_username",
		"transformation",
		"parent_id",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from webhooks after migrate", want)
		}
	}
}

// TestMigrate_AddsColumnsOnUpgrade_SyncState verifies that opening a
// database created by an older binary succeeds and adds newly generated
// columns before CREATE INDEX runs against the pre-existing table. Regression
// coverage for parent_id upgrades and indexed generated columns.
func TestMigrate_AddsColumnsOnUpgrade_SyncState(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")

	// Pre-create the DB with the older table shape: id, data, synced_at and
	// none of the newer generated columns. user_version stays 0 (pre-gate).
	raw, err := sql.Open("sqlite", dbPath)
	if err != nil {
		t.Fatalf("open raw: %v", err)
	}
	if _, err := raw.Exec(`CREATE TABLE sync_state (
		id TEXT PRIMARY KEY,
		data JSON NOT NULL,
		synced_at DATETIME DEFAULT CURRENT_TIMESTAMP
	)`); err != nil {
		raw.Close()
		t.Fatalf("create old table: %v", err)
	}
	raw.Close()

	// Opening with the new binary must run CREATE INDEX statements without
	// erroring on missing generated columns.
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open upgraded db: %v", err)
	}
	defer s.Close()

	// The migration must have added every generated column.
	rows, err := s.DB().Query(`PRAGMA table_info(sync_state)`)
	if err != nil {
		t.Fatalf("table_info: %v", err)
	}
	defer rows.Close()

	hasColumn := make(map[string]bool)
	for rows.Next() {
		var cid int
		var name, typ string
		var notnull, pk int
		var dflt sql.NullString
		if err := rows.Scan(&cid, &name, &typ, &notnull, &dflt, &pk); err != nil {
			t.Fatalf("scan: %v", err)
		}
		hasColumn[name] = true
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("rows: %v", err)
	}

	for _, want := range []string{
		"last_cursor",
		"last_synced_at",
		"total_count",
	} {
		if !hasColumn[want] {
			t.Fatalf("%s column missing from sync_state after migrate", want)
		}
	}
}
