// Copyright 2026 Adam Harris. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "name", "uuid", "slug", "key", "code", "uid"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesAiActionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed ai_actions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAiActionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("ai_actions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "ai_actions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "ai_actions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count ai_actions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("ai_actions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsAiActionsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsAiActionsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("ai_actions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "ai_actions")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesApiKeysTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed api_keys table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesApiKeysTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("api_keys", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "api_keys").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "api_keys")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count api_keys: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("api_keys count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsApiKeysParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsApiKeysParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("api_keys", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "api_keys")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesAppInstallationsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed app_installations table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAppInstallationsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("app_installations", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "app_installations").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "app_installations")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count app_installations: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("app_installations count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAssetsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed assets table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAssetsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "assets").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "assets")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count assets: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("assets count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsAssetsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsAssetsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "assets")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesCommentsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed comments table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesCommentsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("comments", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "comments").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "comments")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count comments: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("comments count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsCommentsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsCommentsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("comments", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "comments")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesContentTypeSnapshotsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed content_type_snapshots table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesContentTypeSnapshotsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("content_type_snapshots", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content_type_snapshots").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content_type_snapshots")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content_type_snapshots: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("content_type_snapshots count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsContentTypeSnapshotsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsContentTypeSnapshotsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("content_type_snapshots", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "content_type_snapshots")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesContentTypesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed content_types table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesContentTypesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("content_types", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "content_types").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "content_types")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count content_types: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("content_types count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsContentTypesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsContentTypesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("content_types", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "content_types")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesDeliveryAssetsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed delivery_assets table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDeliveryAssetsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "delivery_assets").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "delivery_assets")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count delivery_assets: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("delivery_assets count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsDeliveryAssetsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsDeliveryAssetsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "delivery_assets")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesDeliveryContentTypesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed delivery_content_types table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDeliveryContentTypesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_content_types", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "delivery_content_types").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "delivery_content_types")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count delivery_content_types: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("delivery_content_types count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsDeliveryContentTypesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsDeliveryContentTypesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_content_types", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "delivery_content_types")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesDeliveryEntriesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed delivery_entries table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDeliveryEntriesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "delivery_entries").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "delivery_entries")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count delivery_entries: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("delivery_entries count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsDeliveryEntriesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsDeliveryEntriesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "delivery_entries")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesDeliveryLocalesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed delivery_locales table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDeliveryLocalesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_locales", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "delivery_locales").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "delivery_locales")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count delivery_locales: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("delivery_locales count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesDeliverySyncTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed delivery_sync table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesDeliverySyncTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_sync", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "delivery_sync").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "delivery_sync")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count delivery_sync: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("delivery_sync count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsDeliverySyncParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsDeliverySyncParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("delivery_sync", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "delivery_sync")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesEditorInterfacesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed editor_interfaces table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEditorInterfacesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("editor_interfaces", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "editor_interfaces").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "editor_interfaces")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count editor_interfaces: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("editor_interfaces count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEntriesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed entries table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEntriesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "entries").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "entries")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count entries: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("entries count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsEntriesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsEntriesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "entries")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesEntrySnapshotsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed entry_snapshots table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEntrySnapshotsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("entry_snapshots", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "entry_snapshots").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "entry_snapshots")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count entry_snapshots: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("entry_snapshots count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsEntrySnapshotsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsEntrySnapshotsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("entry_snapshots", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "entry_snapshots")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesEnvironmentAliasesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed environment_aliases table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEnvironmentAliasesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("environment_aliases", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "environment_aliases").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "environment_aliases")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count environment_aliases: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("environment_aliases count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesEnvironmentsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed environments table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesEnvironmentsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("environments", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "environments").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "environments")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count environments: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("environments count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsEnvironmentsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsEnvironmentsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("environments", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "environments")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesExtensionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed extensions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesExtensionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("extensions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "extensions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "extensions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count extensions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("extensions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesLocalesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed locales table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesLocalesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("locales", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "locales").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "locales")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count locales: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("locales count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesOrganizationMembershipsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed organization_memberships table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesOrganizationMembershipsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("organization_memberships", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "organization_memberships").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "organization_memberships")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count organization_memberships: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("organization_memberships count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsOrganizationMembershipsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsOrganizationMembershipsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("organization_memberships", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "organization_memberships")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesOrganizationsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed organizations table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesOrganizationsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("organizations", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "organizations").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "organizations")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count organizations: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("organizations count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesPreviewApiKeysTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed preview_api_keys table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPreviewApiKeysTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("preview_api_keys", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "preview_api_keys").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "preview_api_keys")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count preview_api_keys: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("preview_api_keys count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsPreviewApiKeysParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsPreviewApiKeysParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("preview_api_keys", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "preview_api_keys")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesPreviewAssetsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed preview_assets table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPreviewAssetsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("preview_assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "preview_assets").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "preview_assets")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count preview_assets: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("preview_assets count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsPreviewAssetsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsPreviewAssetsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("preview_assets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "preview_assets")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesPreviewEntriesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed preview_entries table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesPreviewEntriesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("preview_entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "preview_entries").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "preview_entries")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count preview_entries: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("preview_entries count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsPreviewEntriesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsPreviewEntriesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("preview_entries", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "preview_entries")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesReleaseActionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed release_actions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesReleaseActionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("release_actions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "release_actions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "release_actions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count release_actions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("release_actions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesReleasesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed releases table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesReleasesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("releases", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "releases").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "releases")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count releases: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("releases count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsReleasesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsReleasesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("releases", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "releases")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesRolesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed roles table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesRolesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("roles", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "roles").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "roles")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count roles: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("roles count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsRolesParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsRolesParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("roles", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "roles")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesScheduledActionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed scheduled_actions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesScheduledActionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("scheduled_actions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "scheduled_actions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "scheduled_actions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count scheduled_actions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("scheduled_actions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSpaceMembershipsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed space_memberships table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSpaceMembershipsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("space_memberships", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "space_memberships").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "space_memberships")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count space_memberships: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("space_memberships count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsSpaceMembershipsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsSpaceMembershipsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("space_memberships", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "space_memberships")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesSpacesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed spaces table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSpacesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("spaces", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "spaces").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "spaces")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count spaces: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("spaces count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTagsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tags table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTagsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tags").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tags")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tags: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tags count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsTagsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsTagsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "tags")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesTasksTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tasks table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTasksTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("tasks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tasks").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tasks")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tasks: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tasks count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsTasksParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsTasksParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("tasks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "tasks")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesUsersTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed users table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesUsersTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("users", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "users").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "users")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count users: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("users count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesWebhookCallsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed webhook_calls table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesWebhookCallsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("webhook_calls", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "webhook_calls").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "webhook_calls")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count webhook_calls: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("webhook_calls count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsWebhookCallsParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsWebhookCallsParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("webhook_calls", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "webhook_calls")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}

// TestUpsertBatch_PopulatesWebhooksTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed webhooks table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesWebhooksTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("webhooks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "webhooks").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "webhooks")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count webhooks: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("webhooks count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_SetsWebhooksParentID verifies that dependent-resource
// sync (which injects parent_id into each item's JSON) populates the typed
// parent_id column when items go through UpsertBatch. Regression for issue #268.
func TestUpsertBatch_SetsWebhooksParentID(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "child-001", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-002", "parent_id": "parent-A"}`),
		json.RawMessage(`{"id": "child-003", "parent_id": "parent-B"}`),
	}
	if _, _, err := s.UpsertBatch("webhooks", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var matchedA int
	parentQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s" WHERE parent_id = ?`, "webhooks")
	if err := db.QueryRow(parentQuery, "parent-A").Scan(&matchedA); err != nil {
		t.Fatalf("count by parent_id: %v", err)
	}
	if matchedA != 2 {
		t.Fatalf("parent_id=parent-A count = %d, want 2 (parent_id column not populated)", matchedA)
	}
}
